-- Generated by lampe

import «std-1.0.0-beta.25».Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_trait_impl[«std-1.0.0-beta.25».impl_84]<> «std-1.0.0-beta.25»::cmp::Eq<> for Field where [] := {
  noir_def eq<>(self: Field, other: Field) -> bool := {
    (#_fEq returning bool)(self, other)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_85]<> «std-1.0.0-beta.25»::cmp::Eq<> for u128 where [] := {
  noir_def eq<>(self: u128, other: u128) -> bool := {
    (#_uEq returning bool)(self, other)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_86]<> «std-1.0.0-beta.25»::cmp::Eq<> for u64 where [] := {
  noir_def eq<>(self: u64, other: u64) -> bool := {
    (#_uEq returning bool)(self, other)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_87]<> «std-1.0.0-beta.25»::cmp::Eq<> for u32 where [] := {
  noir_def eq<>(self: u32, other: u32) -> bool := {
    (#_uEq returning bool)(self, other)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_88]<> «std-1.0.0-beta.25»::cmp::Eq<> for u16 where [] := {
  noir_def eq<>(self: u16, other: u16) -> bool := {
    (#_uEq returning bool)(self, other)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_89]<> «std-1.0.0-beta.25»::cmp::Eq<> for u8 where [] := {
  noir_def eq<>(self: u8, other: u8) -> bool := {
    (#_uEq returning bool)(self, other)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_90]<> «std-1.0.0-beta.25»::cmp::Eq<> for i8 where [] := {
  noir_def eq<>(self: i8, other: i8) -> bool := {
    (#_iEq returning bool)(self, other)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_91]<> «std-1.0.0-beta.25»::cmp::Eq<> for i16 where [] := {
  noir_def eq<>(self: i16, other: i16) -> bool := {
    (#_iEq returning bool)(self, other)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_92]<> «std-1.0.0-beta.25»::cmp::Eq<> for i32 where [] := {
  noir_def eq<>(self: i32, other: i32) -> bool := {
    (#_iEq returning bool)(self, other)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_93]<> «std-1.0.0-beta.25»::cmp::Eq<> for i64 where [] := {
  noir_def eq<>(self: i64, other: i64) -> bool := {
    (#_iEq returning bool)(self, other)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_94]<> «std-1.0.0-beta.25»::cmp::Eq<> for Unit where [] := {
  noir_def eq<>(_self: Unit, _other: Unit) -> bool := {
    #_true
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_95]<> «std-1.0.0-beta.25»::cmp::Eq<> for bool where [] := {
  noir_def eq<>(self: bool, other: bool) -> bool := {
    (#_bEq returning bool)(self, other)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_96]<T: Type, N: u32> «std-1.0.0-beta.25»::cmp::Eq<> for Array<T, N: u32> where [T: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Array<T, N: u32>, other: Array<T, N: u32>) -> bool := {
    let result = (#_ref returning & bool)(#_true);
    for i in (0: u32) .. (#_arrayLen returning u32)(self) do {
      let op_rhs_0 = ((T as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(T, T) -> bool)((#_arrayIndex returning T)(self, (#_cast returning u32)(i)), (#_arrayIndex returning T)(other, (#_cast returning u32)(i)));
      result = (#_bAnd returning bool)((#_readRef returning bool)(result), op_rhs_0);
      #_skip
    };
    (#_readRef returning bool)(result)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_97]<T: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Vector<T> where [T: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Vector<T>, other: Vector<T>) -> bool := {
    let result = (#_ref returning & bool)((#_uEq returning bool)((#_arrayLen returning u32)(self), (#_arrayLen returning u32)(other)));
    if (#_readRef returning bool)(result) then {
      for i in (0: u32) .. (#_arrayLen returning u32)(self) do {
        let op_rhs_0 = ((T as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(T, T) -> bool)((#_vectorIndex returning T)(self, (#_cast returning u32)(i)), (#_vectorIndex returning T)(other, (#_cast returning u32)(i)));
        result = (#_bAnd returning bool)((#_readRef returning bool)(result), op_rhs_0);
        #_skip
      };
      #_skip
    };
    (#_readRef returning bool)(result)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_98]<N: u32> «std-1.0.0-beta.25»::cmp::Eq<> for String<N: u32> where [] := {
  noir_def eq<>(self: String<N: u32>, other: String<N: u32>) -> bool := {
    let self_bytes = (#_strAsBytes returning Array<u8, N: u32>)(self);
    let other_bytes = (#_strAsBytes returning Array<u8, N: u32>)(other);
    ((Array<u8, N: u32> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(Array<u8, N: u32>, Array<u8, N: u32>) -> bool)(self_bytes, other_bytes)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_99]<A: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Tuple<A> where [A: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Tuple<A>, other: Tuple<A>) -> bool := {
    ((A as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(A, A) -> bool)(self.0, other.0)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_100]<A: Type, B: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Tuple<A, B> where [A: «std-1.0.0-beta.25»::cmp::Eq<>, B: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Tuple<A, B>, other: Tuple<A, B>) -> bool := {
    (#_bAnd returning bool)(((A as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(A, A) -> bool)(self.0, other.0), ((B as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(B, B) -> bool)(self.1, other.1))
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_101]<A: Type, B: Type, C: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Tuple<A, B, C> where [A: «std-1.0.0-beta.25»::cmp::Eq<>, B: «std-1.0.0-beta.25»::cmp::Eq<>, C: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Tuple<A, B, C>, other: Tuple<A, B, C>) -> bool := {
    (#_bAnd returning bool)((#_bAnd returning bool)(((A as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(A, A) -> bool)(self.0, other.0), ((B as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(B, B) -> bool)(self.1, other.1)), ((C as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(C, C) -> bool)(self.2, other.2))
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_102]<A: Type, B: Type, C: Type, D: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Tuple<A, B, C, D> where [A: «std-1.0.0-beta.25»::cmp::Eq<>, B: «std-1.0.0-beta.25»::cmp::Eq<>, C: «std-1.0.0-beta.25»::cmp::Eq<>, D: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Tuple<A, B, C, D>, other: Tuple<A, B, C, D>) -> bool := {
    (#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)(((A as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(A, A) -> bool)(self.0, other.0), ((B as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(B, B) -> bool)(self.1, other.1)), ((C as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(C, C) -> bool)(self.2, other.2)), ((D as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(D, D) -> bool)(self.3, other.3))
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_103]<A: Type, B: Type, C: Type, D: Type, E: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Tuple<A, B, C, D, E> where [A: «std-1.0.0-beta.25»::cmp::Eq<>, B: «std-1.0.0-beta.25»::cmp::Eq<>, C: «std-1.0.0-beta.25»::cmp::Eq<>, D: «std-1.0.0-beta.25»::cmp::Eq<>, E: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Tuple<A, B, C, D, E>, other: Tuple<A, B, C, D, E>) -> bool := {
    (#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)(((A as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(A, A) -> bool)(self.0, other.0), ((B as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(B, B) -> bool)(self.1, other.1)), ((C as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(C, C) -> bool)(self.2, other.2)), ((D as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(D, D) -> bool)(self.3, other.3)), ((E as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(E, E) -> bool)(self.4, other.4))
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_104]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Tuple<A, B, C, D, E, F> where [A: «std-1.0.0-beta.25»::cmp::Eq<>, B: «std-1.0.0-beta.25»::cmp::Eq<>, C: «std-1.0.0-beta.25»::cmp::Eq<>, D: «std-1.0.0-beta.25»::cmp::Eq<>, E: «std-1.0.0-beta.25»::cmp::Eq<>, F: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Tuple<A, B, C, D, E, F>, other: Tuple<A, B, C, D, E, F>) -> bool := {
    (#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)(((A as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(A, A) -> bool)(self.0, other.0), ((B as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(B, B) -> bool)(self.1, other.1)), ((C as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(C, C) -> bool)(self.2, other.2)), ((D as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(D, D) -> bool)(self.3, other.3)), ((E as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(E, E) -> bool)(self.4, other.4)), ((F as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(F, F) -> bool)(self.5, other.5))
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_105]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type, G: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Tuple<A, B, C, D, E, F, G> where [A: «std-1.0.0-beta.25»::cmp::Eq<>, B: «std-1.0.0-beta.25»::cmp::Eq<>, C: «std-1.0.0-beta.25»::cmp::Eq<>, D: «std-1.0.0-beta.25»::cmp::Eq<>, E: «std-1.0.0-beta.25»::cmp::Eq<>, F: «std-1.0.0-beta.25»::cmp::Eq<>, G: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Tuple<A, B, C, D, E, F, G>, other: Tuple<A, B, C, D, E, F, G>) -> bool := {
    (#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)(((A as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(A, A) -> bool)(self.0, other.0), ((B as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(B, B) -> bool)(self.1, other.1)), ((C as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(C, C) -> bool)(self.2, other.2)), ((D as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(D, D) -> bool)(self.3, other.3)), ((E as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(E, E) -> bool)(self.4, other.4)), ((F as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(F, F) -> bool)(self.5, other.5)), ((G as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(G, G) -> bool)(self.6, other.6))
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_106]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type, G: Type, H: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Tuple<A, B, C, D, E, F, G, H> where [A: «std-1.0.0-beta.25»::cmp::Eq<>, B: «std-1.0.0-beta.25»::cmp::Eq<>, C: «std-1.0.0-beta.25»::cmp::Eq<>, D: «std-1.0.0-beta.25»::cmp::Eq<>, E: «std-1.0.0-beta.25»::cmp::Eq<>, F: «std-1.0.0-beta.25»::cmp::Eq<>, G: «std-1.0.0-beta.25»::cmp::Eq<>, H: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Tuple<A, B, C, D, E, F, G, H>, other: Tuple<A, B, C, D, E, F, G, H>) -> bool := {
    (#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)(((A as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(A, A) -> bool)(self.0, other.0), ((B as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(B, B) -> bool)(self.1, other.1)), ((C as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(C, C) -> bool)(self.2, other.2)), ((D as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(D, D) -> bool)(self.3, other.3)), ((E as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(E, E) -> bool)(self.4, other.4)), ((F as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(F, F) -> bool)(self.5, other.5)), ((G as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(G, G) -> bool)(self.6, other.6)), ((H as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(H, H) -> bool)(self.7, other.7))
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_107]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type, G: Type, H: Type, I: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Tuple<A, B, C, D, E, F, G, H, I> where [A: «std-1.0.0-beta.25»::cmp::Eq<>, B: «std-1.0.0-beta.25»::cmp::Eq<>, C: «std-1.0.0-beta.25»::cmp::Eq<>, D: «std-1.0.0-beta.25»::cmp::Eq<>, E: «std-1.0.0-beta.25»::cmp::Eq<>, F: «std-1.0.0-beta.25»::cmp::Eq<>, G: «std-1.0.0-beta.25»::cmp::Eq<>, H: «std-1.0.0-beta.25»::cmp::Eq<>, I: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Tuple<A, B, C, D, E, F, G, H, I>, other: Tuple<A, B, C, D, E, F, G, H, I>) -> bool := {
    (#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)(((A as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(A, A) -> bool)(self.0, other.0), ((B as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(B, B) -> bool)(self.1, other.1)), ((C as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(C, C) -> bool)(self.2, other.2)), ((D as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(D, D) -> bool)(self.3, other.3)), ((E as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(E, E) -> bool)(self.4, other.4)), ((F as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(F, F) -> bool)(self.5, other.5)), ((G as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(G, G) -> bool)(self.6, other.6)), ((H as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(H, H) -> bool)(self.7, other.7)), ((I as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(I, I) -> bool)(self.8, other.8))
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_108]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type, G: Type, H: Type, I: Type, J: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Tuple<A, B, C, D, E, F, G, H, I, J> where [A: «std-1.0.0-beta.25»::cmp::Eq<>, B: «std-1.0.0-beta.25»::cmp::Eq<>, C: «std-1.0.0-beta.25»::cmp::Eq<>, D: «std-1.0.0-beta.25»::cmp::Eq<>, E: «std-1.0.0-beta.25»::cmp::Eq<>, F: «std-1.0.0-beta.25»::cmp::Eq<>, G: «std-1.0.0-beta.25»::cmp::Eq<>, H: «std-1.0.0-beta.25»::cmp::Eq<>, I: «std-1.0.0-beta.25»::cmp::Eq<>, J: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Tuple<A, B, C, D, E, F, G, H, I, J>, other: Tuple<A, B, C, D, E, F, G, H, I, J>) -> bool := {
    (#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)(((A as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(A, A) -> bool)(self.0, other.0), ((B as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(B, B) -> bool)(self.1, other.1)), ((C as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(C, C) -> bool)(self.2, other.2)), ((D as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(D, D) -> bool)(self.3, other.3)), ((E as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(E, E) -> bool)(self.4, other.4)), ((F as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(F, F) -> bool)(self.5, other.5)), ((G as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(G, G) -> bool)(self.6, other.6)), ((H as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(H, H) -> bool)(self.7, other.7)), ((I as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(I, I) -> bool)(self.8, other.8)), ((J as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(J, J) -> bool)(self.9, other.9))
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_109]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type, G: Type, H: Type, I: Type, J: Type, K: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Tuple<A, B, C, D, E, F, G, H, I, J, K> where [A: «std-1.0.0-beta.25»::cmp::Eq<>, B: «std-1.0.0-beta.25»::cmp::Eq<>, C: «std-1.0.0-beta.25»::cmp::Eq<>, D: «std-1.0.0-beta.25»::cmp::Eq<>, E: «std-1.0.0-beta.25»::cmp::Eq<>, F: «std-1.0.0-beta.25»::cmp::Eq<>, G: «std-1.0.0-beta.25»::cmp::Eq<>, H: «std-1.0.0-beta.25»::cmp::Eq<>, I: «std-1.0.0-beta.25»::cmp::Eq<>, J: «std-1.0.0-beta.25»::cmp::Eq<>, K: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Tuple<A, B, C, D, E, F, G, H, I, J, K>, other: Tuple<A, B, C, D, E, F, G, H, I, J, K>) -> bool := {
    (#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)(((A as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(A, A) -> bool)(self.0, other.0), ((B as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(B, B) -> bool)(self.1, other.1)), ((C as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(C, C) -> bool)(self.2, other.2)), ((D as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(D, D) -> bool)(self.3, other.3)), ((E as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(E, E) -> bool)(self.4, other.4)), ((F as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(F, F) -> bool)(self.5, other.5)), ((G as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(G, G) -> bool)(self.6, other.6)), ((H as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(H, H) -> bool)(self.7, other.7)), ((I as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(I, I) -> bool)(self.8, other.8)), ((J as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(J, J) -> bool)(self.9, other.9)), ((K as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(K, K) -> bool)(self.10, other.10))
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_110]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type, G: Type, H: Type, I: Type, J: Type, K: Type, L: Type> «std-1.0.0-beta.25»::cmp::Eq<> for Tuple<A, B, C, D, E, F, G, H, I, J, K, L> where [A: «std-1.0.0-beta.25»::cmp::Eq<>, B: «std-1.0.0-beta.25»::cmp::Eq<>, C: «std-1.0.0-beta.25»::cmp::Eq<>, D: «std-1.0.0-beta.25»::cmp::Eq<>, E: «std-1.0.0-beta.25»::cmp::Eq<>, F: «std-1.0.0-beta.25»::cmp::Eq<>, G: «std-1.0.0-beta.25»::cmp::Eq<>, H: «std-1.0.0-beta.25»::cmp::Eq<>, I: «std-1.0.0-beta.25»::cmp::Eq<>, J: «std-1.0.0-beta.25»::cmp::Eq<>, K: «std-1.0.0-beta.25»::cmp::Eq<>, L: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: Tuple<A, B, C, D, E, F, G, H, I, J, K, L>, other: Tuple<A, B, C, D, E, F, G, H, I, J, K, L>) -> bool := {
    (#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)((#_bAnd returning bool)(((A as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(A, A) -> bool)(self.0, other.0), ((B as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(B, B) -> bool)(self.1, other.1)), ((C as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(C, C) -> bool)(self.2, other.2)), ((D as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(D, D) -> bool)(self.3, other.3)), ((E as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(E, E) -> bool)(self.4, other.4)), ((F as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(F, F) -> bool)(self.5, other.5)), ((G as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(G, G) -> bool)(self.6, other.6)), ((H as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(H, H) -> bool)(self.7, other.7)), ((I as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(I, I) -> bool)(self.8, other.8)), ((J as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(J, J) -> bool)(self.9, other.9)), ((K as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(K, K) -> bool)(self.10, other.10)), ((L as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(L, L) -> bool)(self.11, other.11))
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_111]<> «std-1.0.0-beta.25»::cmp::Eq<> for «std-1.0.0-beta.25»::cmp::Ordering<> where [] := {
  noir_def eq<>(self: «std-1.0.0-beta.25»::cmp::Ordering<>, other: «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool := {
    (#_fEq returning bool)(self.0, other.0)
  };
}

noir_def «std-1.0.0-beta.25»::cmp::Ordering::less<>() -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
  (#_makeData returning «std-1.0.0-beta.25»::cmp::Ordering<>)((0: Field))
}

noir_def «std-1.0.0-beta.25»::cmp::Ordering::equal<>() -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
  (#_makeData returning «std-1.0.0-beta.25»::cmp::Ordering<>)((1: Field))
}

noir_def «std-1.0.0-beta.25»::cmp::Ordering::greater<>() -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
  (#_makeData returning «std-1.0.0-beta.25»::cmp::Ordering<>)((2: Field))
}

noir_trait_impl[«std-1.0.0-beta.25».impl_112]<> «std-1.0.0-beta.25»::cmp::Ord<> for u128 where [] := {
  noir_def cmp<>(self: u128, other: u128) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    if (#_uLt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else if (#_uGt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else {
      («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_113]<> «std-1.0.0-beta.25»::cmp::Ord<> for u64 where [] := {
  noir_def cmp<>(self: u64, other: u64) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    if (#_uLt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else if (#_uGt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else {
      («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_114]<> «std-1.0.0-beta.25»::cmp::Ord<> for u32 where [] := {
  noir_def cmp<>(self: u32, other: u32) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    if (#_uLt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else if (#_uGt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else {
      («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_115]<> «std-1.0.0-beta.25»::cmp::Ord<> for u16 where [] := {
  noir_def cmp<>(self: u16, other: u16) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    if (#_uLt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else if (#_uGt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else {
      («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_116]<> «std-1.0.0-beta.25»::cmp::Ord<> for u8 where [] := {
  noir_def cmp<>(self: u8, other: u8) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    if (#_uLt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else if (#_uGt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else {
      («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_117]<> «std-1.0.0-beta.25»::cmp::Ord<> for i8 where [] := {
  noir_def cmp<>(self: i8, other: i8) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    if (#_iLt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else if (#_iGt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else {
      («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_118]<> «std-1.0.0-beta.25»::cmp::Ord<> for i16 where [] := {
  noir_def cmp<>(self: i16, other: i16) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    if (#_iLt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else if (#_iGt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else {
      («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_119]<> «std-1.0.0-beta.25»::cmp::Ord<> for i32 where [] := {
  noir_def cmp<>(self: i32, other: i32) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    if (#_iLt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else if (#_iGt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else {
      («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_120]<> «std-1.0.0-beta.25»::cmp::Ord<> for i64 where [] := {
  noir_def cmp<>(self: i64, other: i64) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    if (#_iLt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else if (#_iGt returning bool)(self, other) then {
      («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else {
      («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_121]<> «std-1.0.0-beta.25»::cmp::Ord<> for Unit where [] := {
  noir_def cmp<>(_self: Unit, _other: Unit) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_122]<> «std-1.0.0-beta.25»::cmp::Ord<> for bool where [] := {
  noir_def cmp<>(self: bool, other: bool) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    if self then {
      if other then {
        («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
      } else {
        («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
      }
    } else if other then {
      («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else {
      («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_123]<T: Type, N: u32> «std-1.0.0-beta.25»::cmp::Ord<> for Array<T, N: u32> where [T: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Array<T, N: u32>, other: Array<T, N: u32>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let result = (#_ref returning & «std-1.0.0-beta.25»::cmp::Ordering<>)((«std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)());
    for i in (0: u32) .. (#_arrayLen returning u32)(self) do {
      if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
        result = ((T as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(T, T) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_arrayIndex returning T)(self, (#_cast returning u32)(i)), (#_arrayIndex returning T)(other, (#_cast returning u32)(i)));
        #_skip
      }
    };
    (#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_124]<T: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Vector<T> where [T: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Vector<T>, other: Vector<T>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let self_len = (#_arrayLen returning u32)(self);
    let other_len = (#_arrayLen returning u32)(other);
    let min_len = if (#_uLt returning bool)(self_len, other_len) then {
      self_len
    } else {
      other_len
    };
    let result = (#_ref returning & «std-1.0.0-beta.25»::cmp::Ordering<>)((«std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)());
    for i in (0: u32) .. min_len do {
      if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
        result = ((T as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(T, T) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_vectorIndex returning T)(self, (#_cast returning u32)(i)), (#_vectorIndex returning T)(other, (#_cast returning u32)(i)));
        #_skip
      }
    };
    if (#_bNot returning bool)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)())) then {
      (#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result)
    } else {
      ((u32 as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(u32, u32) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self_len, other_len)
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_125]<A: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Tuple<A> where [A: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Tuple<A>, other: Tuple<A>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    ((A as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(A, A) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.0, other.0)
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_126]<A: Type, B: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Tuple<A, B> where [A: «std-1.0.0-beta.25»::cmp::Ord<>, B: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Tuple<A, B>, other: Tuple<A, B>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let result = ((A as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(A, A) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.0, other.0);
    if (#_bNot returning bool)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(result, («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)())) then {
      result
    } else {
      ((B as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(B, B) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.1, other.1)
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_127]<A: Type, B: Type, C: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Tuple<A, B, C> where [A: «std-1.0.0-beta.25»::cmp::Ord<>, B: «std-1.0.0-beta.25»::cmp::Ord<>, C: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Tuple<A, B, C>, other: Tuple<A, B, C>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let result = (#_ref returning & «std-1.0.0-beta.25»::cmp::Ordering<>)(((A as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(A, A) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.0, other.0));
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((B as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(B, B) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.1, other.1);
      #_skip
    };
    if (#_bNot returning bool)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)())) then {
      (#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result)
    } else {
      ((C as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(C, C) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.2, other.2)
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_128]<A: Type, B: Type, C: Type, D: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Tuple<A, B, C, D> where [A: «std-1.0.0-beta.25»::cmp::Ord<>, B: «std-1.0.0-beta.25»::cmp::Ord<>, C: «std-1.0.0-beta.25»::cmp::Ord<>, D: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Tuple<A, B, C, D>, other: Tuple<A, B, C, D>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let result = (#_ref returning & «std-1.0.0-beta.25»::cmp::Ordering<>)(((A as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(A, A) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.0, other.0));
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((B as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(B, B) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.1, other.1);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((C as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(C, C) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.2, other.2);
      #_skip
    };
    if (#_bNot returning bool)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)())) then {
      (#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result)
    } else {
      ((D as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(D, D) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.3, other.3)
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_129]<A: Type, B: Type, C: Type, D: Type, E: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Tuple<A, B, C, D, E> where [A: «std-1.0.0-beta.25»::cmp::Ord<>, B: «std-1.0.0-beta.25»::cmp::Ord<>, C: «std-1.0.0-beta.25»::cmp::Ord<>, D: «std-1.0.0-beta.25»::cmp::Ord<>, E: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Tuple<A, B, C, D, E>, other: Tuple<A, B, C, D, E>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let result = (#_ref returning & «std-1.0.0-beta.25»::cmp::Ordering<>)(((A as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(A, A) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.0, other.0));
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((B as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(B, B) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.1, other.1);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((C as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(C, C) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.2, other.2);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((D as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(D, D) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.3, other.3);
      #_skip
    };
    if (#_bNot returning bool)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)())) then {
      (#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result)
    } else {
      ((E as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(E, E) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.4, other.4)
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_130]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Tuple<A, B, C, D, E, F> where [A: «std-1.0.0-beta.25»::cmp::Ord<>, B: «std-1.0.0-beta.25»::cmp::Ord<>, C: «std-1.0.0-beta.25»::cmp::Ord<>, D: «std-1.0.0-beta.25»::cmp::Ord<>, E: «std-1.0.0-beta.25»::cmp::Ord<>, F: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Tuple<A, B, C, D, E, F>, other: Tuple<A, B, C, D, E, F>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let result = (#_ref returning & «std-1.0.0-beta.25»::cmp::Ordering<>)(((A as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(A, A) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.0, other.0));
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((B as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(B, B) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.1, other.1);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((C as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(C, C) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.2, other.2);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((D as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(D, D) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.3, other.3);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((E as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(E, E) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.4, other.4);
      #_skip
    };
    if (#_bNot returning bool)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)())) then {
      (#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result)
    } else {
      ((F as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(F, F) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.5, other.5)
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_131]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type, G: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Tuple<A, B, C, D, E, F, G> where [A: «std-1.0.0-beta.25»::cmp::Ord<>, B: «std-1.0.0-beta.25»::cmp::Ord<>, C: «std-1.0.0-beta.25»::cmp::Ord<>, D: «std-1.0.0-beta.25»::cmp::Ord<>, E: «std-1.0.0-beta.25»::cmp::Ord<>, F: «std-1.0.0-beta.25»::cmp::Ord<>, G: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Tuple<A, B, C, D, E, F, G>, other: Tuple<A, B, C, D, E, F, G>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let result = (#_ref returning & «std-1.0.0-beta.25»::cmp::Ordering<>)(((A as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(A, A) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.0, other.0));
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((B as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(B, B) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.1, other.1);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((C as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(C, C) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.2, other.2);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((D as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(D, D) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.3, other.3);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((E as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(E, E) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.4, other.4);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((F as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(F, F) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.5, other.5);
      #_skip
    };
    if (#_bNot returning bool)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)())) then {
      (#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result)
    } else {
      ((G as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(G, G) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.6, other.6)
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_132]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type, G: Type, H: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Tuple<A, B, C, D, E, F, G, H> where [A: «std-1.0.0-beta.25»::cmp::Ord<>, B: «std-1.0.0-beta.25»::cmp::Ord<>, C: «std-1.0.0-beta.25»::cmp::Ord<>, D: «std-1.0.0-beta.25»::cmp::Ord<>, E: «std-1.0.0-beta.25»::cmp::Ord<>, F: «std-1.0.0-beta.25»::cmp::Ord<>, G: «std-1.0.0-beta.25»::cmp::Ord<>, H: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Tuple<A, B, C, D, E, F, G, H>, other: Tuple<A, B, C, D, E, F, G, H>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let result = (#_ref returning & «std-1.0.0-beta.25»::cmp::Ordering<>)(((A as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(A, A) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.0, other.0));
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((B as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(B, B) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.1, other.1);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((C as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(C, C) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.2, other.2);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((D as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(D, D) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.3, other.3);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((E as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(E, E) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.4, other.4);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((F as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(F, F) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.5, other.5);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((G as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(G, G) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.6, other.6);
      #_skip
    };
    if (#_bNot returning bool)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)())) then {
      (#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result)
    } else {
      ((H as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(H, H) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.7, other.7)
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_133]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type, G: Type, H: Type, I: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Tuple<A, B, C, D, E, F, G, H, I> where [A: «std-1.0.0-beta.25»::cmp::Ord<>, B: «std-1.0.0-beta.25»::cmp::Ord<>, C: «std-1.0.0-beta.25»::cmp::Ord<>, D: «std-1.0.0-beta.25»::cmp::Ord<>, E: «std-1.0.0-beta.25»::cmp::Ord<>, F: «std-1.0.0-beta.25»::cmp::Ord<>, G: «std-1.0.0-beta.25»::cmp::Ord<>, H: «std-1.0.0-beta.25»::cmp::Ord<>, I: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Tuple<A, B, C, D, E, F, G, H, I>, other: Tuple<A, B, C, D, E, F, G, H, I>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let result = (#_ref returning & «std-1.0.0-beta.25»::cmp::Ordering<>)(((A as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(A, A) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.0, other.0));
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((B as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(B, B) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.1, other.1);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((C as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(C, C) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.2, other.2);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((D as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(D, D) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.3, other.3);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((E as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(E, E) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.4, other.4);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((F as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(F, F) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.5, other.5);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((G as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(G, G) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.6, other.6);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((H as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(H, H) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.7, other.7);
      #_skip
    };
    if (#_bNot returning bool)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)())) then {
      (#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result)
    } else {
      ((I as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(I, I) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.8, other.8)
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_134]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type, G: Type, H: Type, I: Type, J: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Tuple<A, B, C, D, E, F, G, H, I, J> where [A: «std-1.0.0-beta.25»::cmp::Ord<>, B: «std-1.0.0-beta.25»::cmp::Ord<>, C: «std-1.0.0-beta.25»::cmp::Ord<>, D: «std-1.0.0-beta.25»::cmp::Ord<>, E: «std-1.0.0-beta.25»::cmp::Ord<>, F: «std-1.0.0-beta.25»::cmp::Ord<>, G: «std-1.0.0-beta.25»::cmp::Ord<>, H: «std-1.0.0-beta.25»::cmp::Ord<>, I: «std-1.0.0-beta.25»::cmp::Ord<>, J: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Tuple<A, B, C, D, E, F, G, H, I, J>, other: Tuple<A, B, C, D, E, F, G, H, I, J>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let result = (#_ref returning & «std-1.0.0-beta.25»::cmp::Ordering<>)(((A as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(A, A) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.0, other.0));
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((B as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(B, B) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.1, other.1);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((C as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(C, C) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.2, other.2);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((D as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(D, D) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.3, other.3);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((E as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(E, E) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.4, other.4);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((F as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(F, F) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.5, other.5);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((G as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(G, G) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.6, other.6);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((H as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(H, H) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.7, other.7);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((I as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(I, I) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.8, other.8);
      #_skip
    };
    if (#_bNot returning bool)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)())) then {
      (#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result)
    } else {
      ((J as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(J, J) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.9, other.9)
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_135]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type, G: Type, H: Type, I: Type, J: Type, K: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Tuple<A, B, C, D, E, F, G, H, I, J, K> where [A: «std-1.0.0-beta.25»::cmp::Ord<>, B: «std-1.0.0-beta.25»::cmp::Ord<>, C: «std-1.0.0-beta.25»::cmp::Ord<>, D: «std-1.0.0-beta.25»::cmp::Ord<>, E: «std-1.0.0-beta.25»::cmp::Ord<>, F: «std-1.0.0-beta.25»::cmp::Ord<>, G: «std-1.0.0-beta.25»::cmp::Ord<>, H: «std-1.0.0-beta.25»::cmp::Ord<>, I: «std-1.0.0-beta.25»::cmp::Ord<>, J: «std-1.0.0-beta.25»::cmp::Ord<>, K: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Tuple<A, B, C, D, E, F, G, H, I, J, K>, other: Tuple<A, B, C, D, E, F, G, H, I, J, K>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let result = (#_ref returning & «std-1.0.0-beta.25»::cmp::Ordering<>)(((A as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(A, A) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.0, other.0));
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((B as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(B, B) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.1, other.1);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((C as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(C, C) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.2, other.2);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((D as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(D, D) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.3, other.3);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((E as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(E, E) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.4, other.4);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((F as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(F, F) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.5, other.5);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((G as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(G, G) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.6, other.6);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((H as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(H, H) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.7, other.7);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((I as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(I, I) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.8, other.8);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((J as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(J, J) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.9, other.9);
      #_skip
    };
    if (#_bNot returning bool)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)())) then {
      (#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result)
    } else {
      ((K as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(K, K) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.10, other.10)
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_136]<A: Type, B: Type, C: Type, D: Type, E: Type, F: Type, G: Type, H: Type, I: Type, J: Type, K: Type, L: Type> «std-1.0.0-beta.25»::cmp::Ord<> for Tuple<A, B, C, D, E, F, G, H, I, J, K, L> where [A: «std-1.0.0-beta.25»::cmp::Ord<>, B: «std-1.0.0-beta.25»::cmp::Ord<>, C: «std-1.0.0-beta.25»::cmp::Ord<>, D: «std-1.0.0-beta.25»::cmp::Ord<>, E: «std-1.0.0-beta.25»::cmp::Ord<>, F: «std-1.0.0-beta.25»::cmp::Ord<>, G: «std-1.0.0-beta.25»::cmp::Ord<>, H: «std-1.0.0-beta.25»::cmp::Ord<>, I: «std-1.0.0-beta.25»::cmp::Ord<>, J: «std-1.0.0-beta.25»::cmp::Ord<>, K: «std-1.0.0-beta.25»::cmp::Ord<>, L: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: Tuple<A, B, C, D, E, F, G, H, I, J, K, L>, other: Tuple<A, B, C, D, E, F, G, H, I, J, K, L>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    let result = (#_ref returning & «std-1.0.0-beta.25»::cmp::Ordering<>)(((A as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(A, A) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.0, other.0));
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((B as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(B, B) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.1, other.1);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((C as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(C, C) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.2, other.2);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((D as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(D, D) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.3, other.3);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((E as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(E, E) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.4, other.4);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((F as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(F, F) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.5, other.5);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((G as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(G, G) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.6, other.6);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((H as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(H, H) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.7, other.7);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((I as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(I, I) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.8, other.8);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((J as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(J, J) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.9, other.9);
      #_skip
    };
    if ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()) then {
      result = ((K as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(K, K) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.10, other.10);
      #_skip
    };
    if (#_bNot returning bool)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)((#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)())) then {
      (#_readRef returning «std-1.0.0-beta.25»::cmp::Ordering<>)(result)
    } else {
      ((L as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(L, L) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.11, other.11)
    }
  };
}

noir_def «std-1.0.0-beta.25»::cmp::max<T: Type>(v1: T, v2: T) -> T := {
  if {
    let __0 = ((T as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(T, T) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(v1, v2);
    let __1 = («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)();
    ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(__0, __1)
  } then {
    v1
  } else {
    v2
  }
}

noir_def «std-1.0.0-beta.25»::cmp::min<T: Type>(v1: T, v2: T) -> T := {
  if {
    let __0 = ((T as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(T, T) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(v1, v2);
    let __1 = («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)();
    ((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(__0, __1)
  } then {
    v2
  } else {
    v1
  }
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::sanity_check_min<>() -> Unit := {
  (#_assert returning Unit)((#_uEq returning bool)((«std-1.0.0-beta.25»::cmp::min<u64> as λ(u64, u64) -> u64)((0: u64), (1: u64)), (0: u64)));
  (#_assert returning Unit)((#_uEq returning bool)((«std-1.0.0-beta.25»::cmp::min<u64> as λ(u64, u64) -> u64)((0: u64), (0: u64)), (0: u64)));
  (#_assert returning Unit)((#_uEq returning bool)((«std-1.0.0-beta.25»::cmp::min<u64> as λ(u64, u64) -> u64)((1: u64), (1: u64)), (1: u64)));
  (#_assert returning Unit)((#_uEq returning bool)((«std-1.0.0-beta.25»::cmp::min<u8> as λ(u8, u8) -> u8)((255: u8), (0: u8)), (0: u8)));
  #_skip
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::sanity_check_max<>() -> Unit := {
  (#_assert returning Unit)((#_uEq returning bool)((«std-1.0.0-beta.25»::cmp::max<u64> as λ(u64, u64) -> u64)((0: u64), (1: u64)), (1: u64)));
  (#_assert returning Unit)((#_uEq returning bool)((«std-1.0.0-beta.25»::cmp::max<u64> as λ(u64, u64) -> u64)((0: u64), (0: u64)), (0: u64)));
  (#_assert returning Unit)((#_uEq returning bool)((«std-1.0.0-beta.25»::cmp::max<u64> as λ(u64, u64) -> u64)((1: u64), (1: u64)), (1: u64)));
  (#_assert returning Unit)((#_uEq returning bool)((«std-1.0.0-beta.25»::cmp::max<u8> as λ(u8, u8) -> u8)((255: u8), (0: u8)), (255: u8)));
  #_skip
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::correctly_handles_unequal_length_vectors<>() -> Unit := {
  let vector_1 = (#_asVector returning Vector<Field>)((#_mkArray returning Array<Field, 4: u32>)((0: Field), (1: Field), (2: Field), (3: Field)));
  let vector_2 = (#_asVector returning Vector<Field>)((#_mkArray returning Array<Field, 3: u32>)((0: Field), (1: Field), (2: Field)));
  (#_assert returning Unit)((#_bNot returning bool)(((Vector<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(Vector<Field>, Vector<Field>) -> bool)(vector_1, vector_2)));
  #_skip
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::lexicographic_ordering_for_vectors<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Vector<u32> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Vector<u32>, Vector<u32>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_asVector returning Vector<u32>)((#_mkArray returning Array<u32, 1: u32>)((2: u32))), (#_asVector returning Vector<u32>)((#_mkArray returning Array<u32, 3: u32>)((1: u32), (1: u32), (1: u32)))), («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Vector<u32> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Vector<u32>, Vector<u32>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_asVector returning Vector<u32>)((#_mkArray returning Array<u32, 2: u32>)((1: u32), (2: u32))), (#_asVector returning Vector<u32>)((#_mkArray returning Array<u32, 3: u32>)((1: u32), (2: u32), (3: u32)))), («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  #_skip
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::eq_unit<>() -> Unit := {
  (#_assert returning Unit)(((Unit as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(Unit, Unit) -> bool)(#_unit, #_unit));
  #_skip
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::eq_bool<>() -> Unit := {
  (#_assert returning Unit)(((bool as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(bool, bool) -> bool)(#_false, #_false));
  (#_assert returning Unit)((#_bNot returning bool)(((bool as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(bool, bool) -> bool)(#_false, #_true)));
  (#_assert returning Unit)((#_bNot returning bool)(((bool as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(bool, bool) -> bool)(#_true, #_false)));
  (#_assert returning Unit)(((bool as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(bool, bool) -> bool)(#_true, #_true));
  #_skip
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::eq_integers<>() -> Unit := {
  #_unit
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::eq_tuples<>() -> Unit := {
  #_unit
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::cmp_unit<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Unit as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Unit, Unit) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(#_unit, #_unit), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  #_skip
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::cmp_bool<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((bool as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(bool, bool) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(#_false, #_true), («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((bool as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(bool, bool) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(#_false, #_false), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((bool as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(bool, bool) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(#_true, #_true), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((bool as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(bool, bool) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(#_true, #_false), («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  #_skip
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::cmp_integers<>() -> Unit := {
  #_unit
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::cmp_tuples<>() -> Unit := {
  #_unit
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::cmp_array<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Array<u8, 3: u32> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Array<u8, 3: u32>, Array<u8, 3: u32>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_mkArray returning Array<u8, 3: u32>)((1: u8), (2: u8), (3: u8)), (#_mkArray returning Array<u8, 3: u32>)((1: u8), (2: u8), (3: u8))), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Array<u8, 3: u32> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Array<u8, 3: u32>, Array<u8, 3: u32>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_mkArray returning Array<u8, 3: u32>)((1: u8), (2: u8), (3: u8)), (#_mkArray returning Array<u8, 3: u32>)((1: u8), (3: u8), (2: u8))), («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Array<u8, 3: u32> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Array<u8, 3: u32>, Array<u8, 3: u32>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_mkArray returning Array<u8, 3: u32>)((1: u8), (3: u8), (3: u8)), (#_mkArray returning Array<u8, 3: u32>)((1: u8), (2: u8), (3: u8))), («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  #_skip
}

noir_def «std-1.0.0-beta.25»::cmp::cmp_tests::cmp_vectors<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Vector<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Vector<u8>, Vector<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_mkVector returning Vector<u8>)((1: u8), (2: u8), (3: u8)), (#_mkVector returning Vector<u8>)((1: u8), (2: u8), (3: u8))), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Vector<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Vector<u8>, Vector<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_mkVector returning Vector<u8>)((1: u8), (3: u8), (3: u8)), (#_mkVector returning Vector<u8>)((1: u8), (2: u8), (3: u8))), («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Vector<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Vector<u8>, Vector<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_mkVector returning Vector<u8>)((1: u8), (2: u8), (3: u8)), (#_mkVector returning Vector<u8>)((1: u8), (3: u8), (3: u8))), («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Vector<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Vector<u8>, Vector<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_mkVector returning Vector<u8>)((1: u8), (2: u8)), (#_mkVector returning Vector<u8>)((1: u8), (2: u8), (3: u8))), («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Vector<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Vector<u8>, Vector<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_mkVector returning Vector<u8>)((1: u8), (2: u8), (3: u8)), (#_mkVector returning Vector<u8>)((1: u8), (2: u8))), («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Vector<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Vector<u8>, Vector<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_mkVector returning Vector<u8>)((10: u8), (0: u8)), (#_mkVector returning Vector<u8>)((9: u8))), («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Vector<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Vector<u8>, Vector<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_mkVector returning Vector<u8>)((9: u8), (0: u8)), (#_mkVector returning Vector<u8>)((10: u8))), («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Vector<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Vector<u8>, Vector<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_mkVector returning Vector<u8>)((9: u8)), (#_mkVector returning Vector<u8>)((10: u8), (0: u8))), («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((Vector<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(Vector<u8>, Vector<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)((#_mkVector returning Vector<u8>)((10: u8)), (#_mkVector returning Vector<u8>)((9: u8), (0: u8))), («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  #_skip
}

def «std-1.0.0-beta.25».Cmp.env : Env := Env.mk
  [«std-1.0.0-beta.25::cmp::Ordering::less», «std-1.0.0-beta.25::cmp::Ordering::equal», «std-1.0.0-beta.25::cmp::Ordering::greater», «std-1.0.0-beta.25::cmp::max», «std-1.0.0-beta.25::cmp::min», «std-1.0.0-beta.25::cmp::cmp_tests::sanity_check_min», «std-1.0.0-beta.25::cmp::cmp_tests::sanity_check_max», «std-1.0.0-beta.25::cmp::cmp_tests::correctly_handles_unequal_length_vectors», «std-1.0.0-beta.25::cmp::cmp_tests::lexicographic_ordering_for_vectors», «std-1.0.0-beta.25::cmp::cmp_tests::eq_unit», «std-1.0.0-beta.25::cmp::cmp_tests::eq_bool», «std-1.0.0-beta.25::cmp::cmp_tests::eq_integers», «std-1.0.0-beta.25::cmp::cmp_tests::eq_tuples», «std-1.0.0-beta.25::cmp::cmp_tests::cmp_unit», «std-1.0.0-beta.25::cmp::cmp_tests::cmp_bool», «std-1.0.0-beta.25::cmp::cmp_tests::cmp_integers», «std-1.0.0-beta.25::cmp::cmp_tests::cmp_tuples», «std-1.0.0-beta.25::cmp::cmp_tests::cmp_array», «std-1.0.0-beta.25::cmp::cmp_tests::cmp_vectors»]
  [«std-1.0.0-beta.25».impl_84, «std-1.0.0-beta.25».impl_85, «std-1.0.0-beta.25».impl_86, «std-1.0.0-beta.25».impl_87, «std-1.0.0-beta.25».impl_88, «std-1.0.0-beta.25».impl_89, «std-1.0.0-beta.25».impl_90, «std-1.0.0-beta.25».impl_91, «std-1.0.0-beta.25».impl_92, «std-1.0.0-beta.25».impl_93, «std-1.0.0-beta.25».impl_94, «std-1.0.0-beta.25».impl_95, «std-1.0.0-beta.25».impl_96, «std-1.0.0-beta.25».impl_97, «std-1.0.0-beta.25».impl_98, «std-1.0.0-beta.25».impl_99, «std-1.0.0-beta.25».impl_100, «std-1.0.0-beta.25».impl_101, «std-1.0.0-beta.25».impl_102, «std-1.0.0-beta.25».impl_103, «std-1.0.0-beta.25».impl_104, «std-1.0.0-beta.25».impl_105, «std-1.0.0-beta.25».impl_106, «std-1.0.0-beta.25».impl_107, «std-1.0.0-beta.25».impl_108, «std-1.0.0-beta.25».impl_109, «std-1.0.0-beta.25».impl_110, «std-1.0.0-beta.25».impl_111, «std-1.0.0-beta.25».impl_112, «std-1.0.0-beta.25».impl_113, «std-1.0.0-beta.25».impl_114, «std-1.0.0-beta.25».impl_115, «std-1.0.0-beta.25».impl_116, «std-1.0.0-beta.25».impl_117, «std-1.0.0-beta.25».impl_118, «std-1.0.0-beta.25».impl_119, «std-1.0.0-beta.25».impl_120, «std-1.0.0-beta.25».impl_121, «std-1.0.0-beta.25».impl_122, «std-1.0.0-beta.25».impl_123, «std-1.0.0-beta.25».impl_124, «std-1.0.0-beta.25».impl_125, «std-1.0.0-beta.25».impl_126, «std-1.0.0-beta.25».impl_127, «std-1.0.0-beta.25».impl_128, «std-1.0.0-beta.25».impl_129, «std-1.0.0-beta.25».impl_130, «std-1.0.0-beta.25».impl_131, «std-1.0.0-beta.25».impl_132, «std-1.0.0-beta.25».impl_133, «std-1.0.0-beta.25».impl_134, «std-1.0.0-beta.25».impl_135, «std-1.0.0-beta.25».impl_136]
