-- Generated by lampe

import «std-1.0.0-beta.25».Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_def «std-1.0.0-beta.25»::option::Option::none<T: Type>() -> «std-1.0.0-beta.25»::option::Option<T> := {
  (#_makeData returning «std-1.0.0-beta.25»::option::Option<T>)(#_false, (#_zeroed returning T)())
}

noir_def «std-1.0.0-beta.25»::option::Option::some<T: Type>(_value: T) -> «std-1.0.0-beta.25»::option::Option<T> := {
  (#_makeData returning «std-1.0.0-beta.25»::option::Option<T>)(#_true, _value)
}

noir_def «std-1.0.0-beta.25»::option::Option::is_none<T: Type>(self: & «std-1.0.0-beta.25»::option::Option<T>) -> bool := {
  (#_bNot returning bool)((#_readRef returning «std-1.0.0-beta.25»::option::Option<T>)(self).0)
}

noir_def «std-1.0.0-beta.25»::option::Option::is_some<T: Type>(self: & «std-1.0.0-beta.25»::option::Option<T>) -> bool := {
  (#_readRef returning «std-1.0.0-beta.25»::option::Option<T>)(self).0
}

noir_def «std-1.0.0-beta.25»::option::Option::unwrap<T: Type>(self: «std-1.0.0-beta.25»::option::Option<T>) -> T := {
  (#_assert returning Unit)(self.0);
  self.1
}

noir_def «std-1.0.0-beta.25»::option::Option::unwrap_unchecked<T: Type>(self: «std-1.0.0-beta.25»::option::Option<T>) -> T := {
  self.1
}

noir_def «std-1.0.0-beta.25»::option::Option::unwrap_or<T: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, default: T) -> T := {
  if self.0 then {
    self.1
  } else {
    default
  }
}

noir_def «std-1.0.0-beta.25»::option::Option::unwrap_or_else<T: Type, Env: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, default: λ() -> T) -> T := {
  if self.0 then {
    self.1
  } else {
    (default as λ() -> T)()
  }
}

noir_def «std-1.0.0-beta.25»::option::Option::expect<T: Type, N: u32, MessageTypes: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, message: FmtString<N: u32, MessageTypes>) -> T := {
  (#_assert returning Unit)((«std-1.0.0-beta.25»::option::Option::is_some<T> as λ(& «std-1.0.0-beta.25»::option::Option<T>) -> bool)((#_ref returning & «std-1.0.0-beta.25»::option::Option<T>)(self)));
  self.1
}

noir_def «std-1.0.0-beta.25»::option::Option::map<T: Type, U: Type, Env: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, f: λ(T) -> U) -> «std-1.0.0-beta.25»::option::Option<U> := {
  if self.0 then {
    («std-1.0.0-beta.25»::option::Option::some<U> as λ(U) -> «std-1.0.0-beta.25»::option::Option<U>)((f as λ(T) -> U)(self.1))
  } else {
    («std-1.0.0-beta.25»::option::Option::none<U> as λ() -> «std-1.0.0-beta.25»::option::Option<U>)()
  }
}

noir_def «std-1.0.0-beta.25»::option::Option::map_or<T: Type, U: Type, Env: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, default: U, f: λ(T) -> U) -> U := {
  if self.0 then {
    (f as λ(T) -> U)(self.1)
  } else {
    default
  }
}

noir_def «std-1.0.0-beta.25»::option::Option::map_or_else<T: Type, U: Type, Env1: Type, Env2: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, default: λ() -> U, f: λ(T) -> U) -> U := {
  if self.0 then {
    (f as λ(T) -> U)(self.1)
  } else {
    (default as λ() -> U)()
  }
}

noir_def «std-1.0.0-beta.25»::option::Option::and<T: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, other: «std-1.0.0-beta.25»::option::Option<T>) -> «std-1.0.0-beta.25»::option::Option<T> := {
  if («std-1.0.0-beta.25»::option::Option::is_none<T> as λ(& «std-1.0.0-beta.25»::option::Option<T>) -> bool)((#_ref returning & «std-1.0.0-beta.25»::option::Option<T>)(self)) then {
    («std-1.0.0-beta.25»::option::Option::none<T> as λ() -> «std-1.0.0-beta.25»::option::Option<T>)()
  } else {
    other
  }
}

noir_def «std-1.0.0-beta.25»::option::Option::and_then<T: Type, U: Type, Env: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, f: λ(T) -> «std-1.0.0-beta.25»::option::Option<U>) -> «std-1.0.0-beta.25»::option::Option<U> := {
  if self.0 then {
    (f as λ(T) -> «std-1.0.0-beta.25»::option::Option<U>)(self.1)
  } else {
    («std-1.0.0-beta.25»::option::Option::none<U> as λ() -> «std-1.0.0-beta.25»::option::Option<U>)()
  }
}

noir_def «std-1.0.0-beta.25»::option::Option::or<T: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, other: «std-1.0.0-beta.25»::option::Option<T>) -> «std-1.0.0-beta.25»::option::Option<T> := {
  if self.0 then {
    self
  } else {
    other
  }
}

noir_def «std-1.0.0-beta.25»::option::Option::or_else<T: Type, Env: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, default: λ() -> «std-1.0.0-beta.25»::option::Option<T>) -> «std-1.0.0-beta.25»::option::Option<T> := {
  if self.0 then {
    self
  } else {
    (default as λ() -> «std-1.0.0-beta.25»::option::Option<T>)()
  }
}

noir_def «std-1.0.0-beta.25»::option::Option::xor<T: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, other: «std-1.0.0-beta.25»::option::Option<T>) -> «std-1.0.0-beta.25»::option::Option<T> := {
  if self.0 then {
    if other.0 then {
      («std-1.0.0-beta.25»::option::Option::none<T> as λ() -> «std-1.0.0-beta.25»::option::Option<T>)()
    } else {
      self
    }
  } else if other.0 then {
    other
  } else {
    («std-1.0.0-beta.25»::option::Option::none<T> as λ() -> «std-1.0.0-beta.25»::option::Option<T>)()
  }
}

noir_def «std-1.0.0-beta.25»::option::Option::filter<T: Type, Env: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, predicate: λ(T) -> bool) -> «std-1.0.0-beta.25»::option::Option<T> := {
  if self.0 then {
    if (predicate as λ(T) -> bool)(self.1) then {
      self
    } else {
      («std-1.0.0-beta.25»::option::Option::none<T> as λ() -> «std-1.0.0-beta.25»::option::Option<T>)()
    }
  } else {
    («std-1.0.0-beta.25»::option::Option::none<T> as λ() -> «std-1.0.0-beta.25»::option::Option<T>)()
  }
}

noir_def «std-1.0.0-beta.25»::option::Option::flatten<T: Type>(option: «std-1.0.0-beta.25»::option::Option<«std-1.0.0-beta.25»::option::Option<T> >) -> «std-1.0.0-beta.25»::option::Option<T> := {
  if option.0 then {
    option.1
  } else {
    («std-1.0.0-beta.25»::option::Option::none<T> as λ() -> «std-1.0.0-beta.25»::option::Option<T>)()
  }
}

noir_trait_impl[«std-1.0.0-beta.25».impl_79]<T: Type> «std-1.0.0-beta.25»::default::Default<> for «std-1.0.0-beta.25»::option::Option<T> where [] := {
  noir_def default<>() -> «std-1.0.0-beta.25»::option::Option<T> := {
    («std-1.0.0-beta.25»::option::Option::none<T> as λ() -> «std-1.0.0-beta.25»::option::Option<T>)()
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_80]<T: Type> «std-1.0.0-beta.25»::cmp::Eq<> for «std-1.0.0-beta.25»::option::Option<T> where [T: «std-1.0.0-beta.25»::cmp::Eq<>] := {
  noir_def eq<>(self: «std-1.0.0-beta.25»::option::Option<T>, other: «std-1.0.0-beta.25»::option::Option<T>) -> bool := {
    if (#_bEq returning bool)(self.0, other.0) then {
      if self.0 then {
        ((T as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(T, T) -> bool)(self.1, other.1)
      } else {
        #_true
      }
    } else {
      #_false
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_81]<T: Type> «std-1.0.0-beta.25»::hash::Hash<> for «std-1.0.0-beta.25»::option::Option<T> where [T: «std-1.0.0-beta.25»::hash::Hash<>] := {
  noir_def hash<H: Type>(self: «std-1.0.0-beta.25»::option::Option<T>, state: & H) -> Unit := {
    ((bool as «std-1.0.0-beta.25»::hash::Hash<>)::hash<H> as λ(bool, & H) -> Unit)(self.0, state);
    if self.0 then {
      ((T as «std-1.0.0-beta.25»::hash::Hash<>)::hash<H> as λ(T, & H) -> Unit)(self.1, state);
      #_skip
    }
  };
}

noir_trait_impl[«std-1.0.0-beta.25».impl_82]<T: Type> «std-1.0.0-beta.25»::cmp::Ord<> for «std-1.0.0-beta.25»::option::Option<T> where [T: «std-1.0.0-beta.25»::cmp::Ord<>] := {
  noir_def cmp<>(self: «std-1.0.0-beta.25»::option::Option<T>, other: «std-1.0.0-beta.25»::option::Option<T>) -> «std-1.0.0-beta.25»::cmp::Ordering<> := {
    if self.0 then {
      if other.0 then {
        ((T as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(T, T) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(self.1, other.1)
      } else {
        («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
      }
    } else if other.0 then {
      («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    } else {
      («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()
    }
  };
}

noir_def «std-1.0.0-beta.25»::option::tests::some_and_none<>() -> Unit := {
  (#_assert returning Unit)((«std-1.0.0-beta.25»::option::Option::is_none<u8> as λ(& «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((#_ref returning & «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)())));
  (#_assert returning Unit)((#_bNot returning bool)((«std-1.0.0-beta.25»::option::Option::is_some<u8> as λ(& «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((#_ref returning & «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()))));
  (#_assert returning Unit)((«std-1.0.0-beta.25»::option::Option::is_some<Field> as λ(& «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((#_ref returning & «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)))));
  (#_assert returning Unit)((#_bNot returning bool)((«std-1.0.0-beta.25»::option::Option::is_none<Field> as λ(& «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((#_ref returning & «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field))))));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::unwrap_succeeds<>() -> Unit := {
  (#_assert returning Unit)((#_fEq returning bool)((«std-1.0.0-beta.25»::option::Option::unwrap<Field> as λ(«std-1.0.0-beta.25»::option::Option<Field>) -> Field)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field))), (1: Field)));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::unwrap_fails<>() -> Unit := {
  let __0 = («std-1.0.0-beta.25»::option::Option::unwrap<u8> as λ(«std-1.0.0-beta.25»::option::Option<u8>) -> u8)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)());
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::unwrap_or<>() -> Unit := {
  (#_assert returning Unit)((#_fEq returning bool)((«std-1.0.0-beta.25»::option::Option::unwrap_or<Field> as λ(«std-1.0.0-beta.25»::option::Option<Field>, Field) -> Field)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (2: Field)), (1: Field)));
  (#_assert returning Unit)((#_fEq returning bool)((«std-1.0.0-beta.25»::option::Option::unwrap_or<Field> as λ(«std-1.0.0-beta.25»::option::Option<Field>, Field) -> Field)((«std-1.0.0-beta.25»::option::Option::none<Field> as λ() -> «std-1.0.0-beta.25»::option::Option<Field>)(), (2: Field)), (2: Field)));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::unwrap_or_else<>() -> Unit := {
  (#_assert returning Unit)((#_fEq returning bool)((«std-1.0.0-beta.25»::option::Option::unwrap_or_else<Field, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, λ() -> Field) -> Field)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (fn(): Field := (2: Field))), (1: Field)));
  (#_assert returning Unit)((#_fEq returning bool)((«std-1.0.0-beta.25»::option::Option::unwrap_or_else<Field, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, λ() -> Field) -> Field)((«std-1.0.0-beta.25»::option::Option::none<Field> as λ() -> «std-1.0.0-beta.25»::option::Option<Field>)(), (fn(): Field := (2: Field))), (2: Field)));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::expect_succeeds<>() -> Unit := {
  (#_assert returning Unit)((#_fEq returning bool)((«std-1.0.0-beta.25»::option::Option::expect<Field, 15: u32, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, FmtString<15: u32, Unit>) -> Field)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (#_mkFormatString returning FmtString<15: u32, Unit>)("Should be there")), (1: Field)));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::expect_fails<>() -> Unit := {
  let __0 = («std-1.0.0-beta.25»::option::Option::expect<u8, 15: u32, Unit> as λ(«std-1.0.0-beta.25»::option::Option<u8>, FmtString<15: u32, Unit>) -> u8)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), (#_mkFormatString returning FmtString<15: u32, Unit>)("Should be there"));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::map<>() -> Unit := {
  (#_assert returning Unit)((«std-1.0.0-beta.25»::option::Option::is_none<u8> as λ(& «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((#_ref returning & «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::map<u8, Unit> as λ(«std-1.0.0-beta.25»::option::Option<u8>, λ(u8) -> u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), (fn(x: u8): u8 := (#_uAdd returning u8)(x, (1: u8)))))));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::map<Field, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, λ(Field) -> Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (fn(x: Field): Field := (#_fAdd returning Field)(x, (1: Field)))), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((2: Field))));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::map_or<>() -> Unit := {
  (#_assert returning Unit)((#_uEq returning bool)((«std-1.0.0-beta.25»::option::Option::map_or<u8, Unit> as λ(«std-1.0.0-beta.25»::option::Option<u8>, u8, λ(u8) -> u8) -> u8)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), (0: u8), (fn(x: u8): u8 := (#_uAdd returning u8)(x, (1: u8)))), (0: u8)));
  (#_assert returning Unit)((#_fEq returning bool)((«std-1.0.0-beta.25»::option::Option::map_or<Field, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, Field, λ(Field) -> Field) -> Field)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (0: Field), (fn(x: Field): Field := (#_fAdd returning Field)(x, (1: Field)))), (2: Field)));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::map_or_else<>() -> Unit := {
  (#_assert returning Unit)((#_uEq returning bool)((«std-1.0.0-beta.25»::option::Option::map_or_else<u8, Unit> as λ(«std-1.0.0-beta.25»::option::Option<u8>, λ() -> u8, λ(u8) -> u8) -> u8)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), (fn(): u8 := (0: u8)), (fn(x: u8): u8 := (#_uAdd returning u8)(x, (1: u8)))), (0: u8)));
  (#_assert returning Unit)((#_fEq returning bool)((«std-1.0.0-beta.25»::option::Option::map_or_else<Field, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, λ() -> Field, λ(Field) -> Field) -> Field)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (fn(): Field := (0: Field)), (fn(x: Field): Field := (#_fAdd returning Field)(x, (1: Field)))), (2: Field)));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::and<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::and<u8> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::and<u8> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), («std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8))), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::and<Field> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((2: Field))), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((2: Field))));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::and<Field> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), («std-1.0.0-beta.25»::option::Option::none<Field> as λ() -> «std-1.0.0-beta.25»::option::Option<Field>)()), («std-1.0.0-beta.25»::option::Option::none<Field> as λ() -> «std-1.0.0-beta.25»::option::Option<Field>)()));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::and_then<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::and_then<u8, Unit> as λ(«std-1.0.0-beta.25»::option::Option<u8>, λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), (fn(__0: u8): «std-1.0.0-beta.25»::option::Option<u8> := («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)())), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::and_then<u8, Field, Unit> as λ(«std-1.0.0-beta.25»::option::Option<u8>, λ(u8) -> «std-1.0.0-beta.25»::option::Option<Field>) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), (fn(__1: u8): «std-1.0.0-beta.25»::option::Option<Field> := («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)))), («std-1.0.0-beta.25»::option::Option::none<Field> as λ() -> «std-1.0.0-beta.25»::option::Option<Field>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::and_then<Field, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (fn(x: Field): «std-1.0.0-beta.25»::option::Option<Field> := («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((#_fAdd returning Field)(x, (1: Field))))), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((2: Field))));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::and_then<Field, u8, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, λ(Field) -> «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (fn(__3: Field): «std-1.0.0-beta.25»::option::Option<u8> := («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)())), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::or<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::or<u8> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::or<u8> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), («std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8))), («std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8))));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::or<Field> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((2: Field))), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field))));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::or<Field> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), («std-1.0.0-beta.25»::option::Option::none<Field> as λ() -> «std-1.0.0-beta.25»::option::Option<Field>)()), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field))));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::or_else<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::or_else<u8, Unit> as λ(«std-1.0.0-beta.25»::option::Option<u8>, λ() -> «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), (fn(): «std-1.0.0-beta.25»::option::Option<u8> := («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)())), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::or_else<u8, Unit> as λ(«std-1.0.0-beta.25»::option::Option<u8>, λ() -> «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), (fn(): «std-1.0.0-beta.25»::option::Option<u8> := («std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8)))), («std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8))));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::or_else<Field, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, λ() -> «std-1.0.0-beta.25»::option::Option<Field>) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (fn(): «std-1.0.0-beta.25»::option::Option<Field> := («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((2: Field)))), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field))));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::or_else<Field, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, λ() -> «std-1.0.0-beta.25»::option::Option<Field>) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (fn(): «std-1.0.0-beta.25»::option::Option<Field> := («std-1.0.0-beta.25»::option::Option::none<Field> as λ() -> «std-1.0.0-beta.25»::option::Option<Field>)())), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field))));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::xor<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::xor<u8> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::xor<u8> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), («std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8))), («std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8))));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::xor<Field> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((2: Field))), («std-1.0.0-beta.25»::option::Option::none<Field> as λ() -> «std-1.0.0-beta.25»::option::Option<Field>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::xor<Field> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), («std-1.0.0-beta.25»::option::Option::none<Field> as λ() -> «std-1.0.0-beta.25»::option::Option<Field>)()), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field))));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::filter<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::filter<u8, Unit> as λ(«std-1.0.0-beta.25»::option::Option<u8>, λ(u8) -> bool) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), (fn(__0: u8): bool := #_true)), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::filter<Field, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, λ(Field) -> bool) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (fn(x: Field): bool := (#_fEq returning bool)(x, (1: Field)))), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field))));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::filter<Field, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, λ(Field) -> bool) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (fn(x: Field): bool := (#_fEq returning bool)(x, (2: Field)))), («std-1.0.0-beta.25»::option::Option::none<Field> as λ() -> «std-1.0.0-beta.25»::option::Option<Field>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::filter<Field, Unit> as λ(«std-1.0.0-beta.25»::option::Option<Field>, λ(Field) -> bool) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)), (fn(x: Field): bool := (#_fEq returning bool)(x, (2: Field)))), («std-1.0.0-beta.25»::option::Option::none<Field> as λ() -> «std-1.0.0-beta.25»::option::Option<Field>)()));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::flatten<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::flatten<u8> as λ(«std-1.0.0-beta.25»::option::Option<«std-1.0.0-beta.25»::option::Option<u8> >) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::none<«std-1.0.0-beta.25»::option::Option<u8> > as λ() -> «std-1.0.0-beta.25»::option::Option<«std-1.0.0-beta.25»::option::Option<u8> >)()), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::flatten<u8> as λ(«std-1.0.0-beta.25»::option::Option<«std-1.0.0-beta.25»::option::Option<u8> >) -> «std-1.0.0-beta.25»::option::Option<u8>)((«std-1.0.0-beta.25»::option::Option::some<«std-1.0.0-beta.25»::option::Option<u8> > as λ(«std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::option::Option<«std-1.0.0-beta.25»::option::Option<u8> >)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)())), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<Field> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<Field>, «std-1.0.0-beta.25»::option::Option<Field>) -> bool)((«std-1.0.0-beta.25»::option::Option::flatten<Field> as λ(«std-1.0.0-beta.25»::option::Option<«std-1.0.0-beta.25»::option::Option<Field> >) -> «std-1.0.0-beta.25»::option::Option<Field>)((«std-1.0.0-beta.25»::option::Option::some<«std-1.0.0-beta.25»::option::Option<Field> > as λ(«std-1.0.0-beta.25»::option::Option<Field>) -> «std-1.0.0-beta.25»::option::Option<«std-1.0.0-beta.25»::option::Option<Field> >)((«std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field)))), («std-1.0.0-beta.25»::option::Option::some<Field> as λ(Field) -> «std-1.0.0-beta.25»::option::Option<Field>)((1: Field))));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::default<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::default::Default<>)::default<> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::eq<>() -> Unit := {
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)()));
  (#_assert returning Unit)((#_bNot returning bool)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8)), («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)())));
  (#_assert returning Unit)((#_bNot returning bool)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)(), («std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8)))));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8)), («std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8))));
  (#_assert returning Unit)((#_bNot returning bool)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> bool)((«std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8)), («std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((2: u8)))));
  #_skip
}

noir_def «std-1.0.0-beta.25»::option::tests::cmp<>() -> Unit := {
  let none = («std-1.0.0-beta.25»::option::Option::none<u8> as λ() -> «std-1.0.0-beta.25»::option::Option<u8>)();
  let one = («std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((1: u8));
  let two = («std-1.0.0-beta.25»::option::Option::some<u8> as λ(u8) -> «std-1.0.0-beta.25»::option::Option<u8>)((2: u8));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(none, none), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(none, one), («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(one, none), («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(one, one), («std-1.0.0-beta.25»::cmp::Ordering::equal<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(one, two), («std-1.0.0-beta.25»::cmp::Ordering::less<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  (#_assert returning Unit)(((«std-1.0.0-beta.25»::cmp::Ordering<> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(«std-1.0.0-beta.25»::cmp::Ordering<>, «std-1.0.0-beta.25»::cmp::Ordering<>) -> bool)(((«std-1.0.0-beta.25»::option::Option<u8> as «std-1.0.0-beta.25»::cmp::Ord<>)::cmp<> as λ(«std-1.0.0-beta.25»::option::Option<u8>, «std-1.0.0-beta.25»::option::Option<u8>) -> «std-1.0.0-beta.25»::cmp::Ordering<>)(two, one), («std-1.0.0-beta.25»::cmp::Ordering::greater<> as λ() -> «std-1.0.0-beta.25»::cmp::Ordering<>)()));
  #_skip
}

def «std-1.0.0-beta.25».Option.env : Env := Env.mk
  [«std-1.0.0-beta.25::option::Option::none», «std-1.0.0-beta.25::option::Option::some», «std-1.0.0-beta.25::option::Option::is_none», «std-1.0.0-beta.25::option::Option::is_some», «std-1.0.0-beta.25::option::Option::unwrap», «std-1.0.0-beta.25::option::Option::unwrap_unchecked», «std-1.0.0-beta.25::option::Option::unwrap_or», «std-1.0.0-beta.25::option::Option::unwrap_or_else», «std-1.0.0-beta.25::option::Option::expect», «std-1.0.0-beta.25::option::Option::map», «std-1.0.0-beta.25::option::Option::map_or», «std-1.0.0-beta.25::option::Option::map_or_else», «std-1.0.0-beta.25::option::Option::and», «std-1.0.0-beta.25::option::Option::and_then», «std-1.0.0-beta.25::option::Option::or», «std-1.0.0-beta.25::option::Option::or_else», «std-1.0.0-beta.25::option::Option::xor», «std-1.0.0-beta.25::option::Option::filter», «std-1.0.0-beta.25::option::Option::flatten», «std-1.0.0-beta.25::option::tests::some_and_none», «std-1.0.0-beta.25::option::tests::unwrap_succeeds», «std-1.0.0-beta.25::option::tests::unwrap_fails», «std-1.0.0-beta.25::option::tests::unwrap_or», «std-1.0.0-beta.25::option::tests::unwrap_or_else», «std-1.0.0-beta.25::option::tests::expect_succeeds», «std-1.0.0-beta.25::option::tests::expect_fails», «std-1.0.0-beta.25::option::tests::map», «std-1.0.0-beta.25::option::tests::map_or», «std-1.0.0-beta.25::option::tests::map_or_else», «std-1.0.0-beta.25::option::tests::and», «std-1.0.0-beta.25::option::tests::and_then», «std-1.0.0-beta.25::option::tests::or», «std-1.0.0-beta.25::option::tests::or_else», «std-1.0.0-beta.25::option::tests::xor», «std-1.0.0-beta.25::option::tests::filter», «std-1.0.0-beta.25::option::tests::flatten», «std-1.0.0-beta.25::option::tests::default», «std-1.0.0-beta.25::option::tests::eq», «std-1.0.0-beta.25::option::tests::cmp»]
  [«std-1.0.0-beta.25».impl_79, «std-1.0.0-beta.25».impl_80, «std-1.0.0-beta.25».impl_81, «std-1.0.0-beta.25».impl_82]
