-- Generated by lampe

import «std-1.0.0-beta.25».Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_def «std-1.0.0-beta.25»::string::as_bytes_vec<N: u32>(self: String<N: u32>) -> Vector<u8> := {
  (#_asVector returning Vector<u8>)((#_strAsBytes returning Array<u8, N: u32>)(self))
}

noir_trait_impl[«std-1.0.0-beta.25».impl_83]<N: u32> «std-1.0.0-beta.25»::convert::From<Array<u8, N: u32> > for String<N: u32> where [] := {
  noir_def «from»<>(bytes: Array<u8, N: u32>) -> String<N: u32> := {
    (#_arrayAsStrUnchecked returning String<N: u32>)(bytes)
  };
}

noir_def «std-1.0.0-beta.25»::string::tests::as_bytes<>() -> Unit := {
  (#_assert returning Unit)(((Array<u8, 4: u32> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(Array<u8, 4: u32>, Array<u8, 4: u32>) -> bool)((#_strAsBytes returning Array<u8, 4: u32>)("Noir"), (#_mkArray returning Array<u8, 4: u32>)((78: u8), (111: u8), (105: u8), (114: u8))));
  #_skip
}

noir_def «std-1.0.0-beta.25»::string::tests::as_bytes_vec<>() -> Unit := {
  (#_assert returning Unit)(((Vector<u8> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(Vector<u8>, Vector<u8>) -> bool)((«std-1.0.0-beta.25»::string::as_bytes_vec<4: u32> as λ(String<4: u32>) -> Vector<u8>)("Noir"), (#_mkVector returning Vector<u8>)((78: u8), (111: u8), (105: u8), (114: u8))));
  #_skip
}

noir_def «std-1.0.0-beta.25»::string::tests::from_bytes<>() -> Unit := {
  let str = ((String<4: u32> as «std-1.0.0-beta.25»::convert::From<Array<u8, 4: u32> >)::«from»<> as λ(Array<u8, 4: u32>) -> String<4: u32>)((#_mkArray returning Array<u8, 4: u32>)((78: u8), (111: u8), (105: u8), (114: u8)));
  (#_assert returning Unit)(((String<4: u32> as «std-1.0.0-beta.25»::cmp::Eq<>)::eq<> as λ(String<4: u32>, String<4: u32>) -> bool)(str, "Noir"));
  #_skip
}

def «std-1.0.0-beta.25».String.env : Env := Env.mk
  [«std-1.0.0-beta.25::string::as_bytes_vec», «std-1.0.0-beta.25::string::tests::as_bytes», «std-1.0.0-beta.25::string::tests::as_bytes_vec», «std-1.0.0-beta.25::string::tests::from_bytes»]
  [«std-1.0.0-beta.25».impl_83]
