-- Generated by lampe

import «noir_sort-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

noir_def «noir_sort-0.0.0»::quicksort::quicksort::partition<T: Type, N: u32>(arr: & Array<T, N: u32>, low: u32, high: u32) -> u32 := {
  (#_fresh returning u32)()
}

noir_def «noir_sort-0.0.0»::quicksort::quicksort::quicksort_loop<T: Type, N: u32>(arr: & Array<T, N: u32>, low: u32, high: u32) -> Unit := {
  (#_fresh returning Unit)()
}

noir_def «noir_sort-0.0.0»::quicksort::quicksort::quicksort<T: Type, N: u32>(_arr: Array<T, N: u32>) -> Array<T, N: u32> := {
  (#_fresh returning Array<T, N: u32>)()
}

def «noir_sort-0.0.0».Quicksort.Quicksort.env : Env := Env.mk
  [«noir_sort-0.0.0::quicksort::quicksort::partition», «noir_sort-0.0.0::quicksort::quicksort::quicksort_loop», «noir_sort-0.0.0::quicksort::quicksort::quicksort»]
  []
