-- Generated by lampe

import «ExtractionTests-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

noir_def «ExtractionTests-0.0.0»::array_as_vector::array_as_vector_shorthand<>() -> Vector<bool> := {
  let v = (#_asVector returning Vector<bool>)((#_mkArray returning Array<bool, 1: u32>)(#_false));
  v
}

def «ExtractionTests-0.0.0».ArrayAsVector.env : Env := Env.mk
  [«ExtractionTests-0.0.0::array_as_vector::array_as_vector_shorthand»]
  []
