-- Generated by lampe

import «ExtractionTests-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «ExtractionTests-0.0.0»
namespace Extracted

noir_trait_impl[impl_430]<> associated_type::Foo<> for associated_type::Pair<> where [] := {
  noir_def foo_meth<>(self: associated_type::Pair<>) -> Field := {
    self.0
  };
}


def AssociatedType.env : Env := Env.mk
  []
  [impl_430]
