-- Generated by lampe

import «ExtractionTests-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «ExtractionTests-0.0.0»
namespace Extracted

noir_global_def field_generics::A: Field = (4294967297: Field);

noir_def field_generics::foo1<A: Field>() -> Field := {
  fConst!(A: Field)
}

noir_def field_generics::main<>() -> Unit := {
  let _ = (field_generics::foo1<4294967297: Field> as λ() -> Field)();
  #_skip
}

def FieldGenerics.env : Env := Env.mk
  [«field_generics::A», «field_generics::foo1», «field_generics::main»]
  []
