-- Generated by lampe

import «ExtractionTests-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

noir_trait_impl[«ExtractionTests-0.0.0».impl_434]<I: Type> «ExtractionTests-0.0.0»::multiple_generics::Foo<I> for «ExtractionTests-0.0.0»::multiple_generics::Pair<I> where [] := {
  noir_def foo3<>(self: «ExtractionTests-0.0.0»::multiple_generics::Pair<I>) -> I := {
    self.0
  };
}

def «ExtractionTests-0.0.0».MultipleGenerics.env : Env := Env.mk
  []
  [«ExtractionTests-0.0.0».impl_434]
