-- Generated by lampe

import «ExtractionTests-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

noir_def «ExtractionTests-0.0.0»::oracle::use_oracles<>(x: Field) -> Field := {
  let y = {
    («ExtractionTests-0.0.0»::oracle::foo<> as λ(Field) -> Field)(x)
  };
  let z = {
    («ExtractionTests-0.0.0»::oracle::bar<> as λ() -> Field)()
  };
  (#_fAdd returning Field)(y, z)
}

noir_def «ExtractionTests-0.0.0»::oracle::foo<>(_x: Field) -> Field := {
  (#_fresh returning Field)()
}

noir_def «ExtractionTests-0.0.0»::oracle::bar<>() -> Field := {
  (#_fresh returning Field)()
}

def «ExtractionTests-0.0.0».Oracle.env : Env := Env.mk
  [«ExtractionTests-0.0.0::oracle::use_oracles», «ExtractionTests-0.0.0::oracle::foo», «ExtractionTests-0.0.0::oracle::bar»]
  []
