-- Generated by lampe

import «Merkle-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «Merkle-0.0.0»
namespace Extracted

nr_trait_impl[impl_428] <> hasher::BinaryHasher<Field> for skyscraper::Skyscraper<> where  {
    fn «hash»<> (a : Field, b : Field) -> Field {
        let x = (@permute::permute<> as λ([Field; 2]) → [Field; 2])([a, b]);
        #fAdd(#arrayIndex(x, #cast(0 : u32) : u32) : Field, a) : Field;
}
}


def Skyscraper.Mod.env := Lampe.Env.mk [] [impl_428]