-- Generated by lampe

import Lampe

open Lampe

namespace Unconstrained
namespace «0.0.0»
namespace Extracted
namespace Unconstrained
namespace «0.0.0»

nr_def «fun»<>() -> Field {
    #fresh() : Field
}


def env := Lampe.Env.mk [«fun»] []