use std::path::PathBuf;
use thiserror::Error;

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Debug, Error)]
pub enum Error {
    #[error("File at {_0:?} conflicts with file generated by Lampe at same path in Lean project")]
    DuplicateWithGeneratedFile(PathBuf),
}
