-- Generated by lampe

import Lampe

open Lampe

namespace Multiple
namespace «0.0.0»
namespace Extracted
namespace Multiple
namespace «0.0.0»

nr_type_alias Asdf<> = Field

nr_struct_def bar::Asdf2<> {
    asdf : @Asdf<>
}

nr_type_alias Asdf3<> = bar::Asdf2<>