-- Generated by lampe

import «TestDep-0.0.0».Extracted.Dependencies.«GitDep-2.0.0».GeneratedTypes
import «TestDep-0.0.0».Extracted.Dependencies.«GitDep-2.0.0».Lib

namespace «TestDep-0.0.0»
namespace Extracted
namespace Dependencies
namespace «GitDep-2.0.0»

def env := «TestDep-0.0.0».Extracted.Dependencies.«GitDep-2.0.0».Lib.env
