-- Generated by lampe

import «complexnr-0.0.0».Extracted.GeneratedTypes
import «complexnr-0.0.0».Extracted.Lib
import «std-1.0.0-beta.12».Extracted

namespace «complexnr-0.0.0»

def env := Lib.env
  ++ «std-1.0.0-beta.12».env
