-- Generated by lampe

import Multiple.Extracted.GeneratedTypes
import Lampe

open Lampe

namespace Extracted

nr_def «bar»::«bar»<>(x : Field) -> Field {
    #fAdd(x, 1 : Field) : Field;
}


def Bar.Mod.env := Lampe.Env.mk [«bar::bar»] []