-- Generated by lampe

import Lampe

open Lampe

namespace Globals
namespace «0.0.0»
namespace Extracted
namespace Globals
namespace «0.0.0»

nr_def «FOO»<>() -> Field {
    42 : Field
}

nr_def «FOOS»<>() -> [Field; 2] {
    [(@FOO<> as λ() → Field)(), #fAdd((@FOO<> as λ() → Field)(), 1 : Field) : Field]
}

nr_def «main»<>() -> Field {
    #arrayIndex((@FOOS<> as λ() → [Field; 2])(), #cast(1 : Field) : u32) : Field;
}


def env := Lampe.Env.mk [«FOO», «main», «FOOS»] []