-- Generated by lampe

import «std-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «std-0.0.0»
namespace Extracted

impl<N : U32> «std::meta::ctstring::AsCtString» for String<N> as impl_281 {
  nr_def as_ctstring(self : String<N>) -> Quoted<CtString> := {
    (str_as_ctstring<TV_'140> as λ(String<N>) -> Quoted<CtString>)(self)
  }
}

impl<N : U32, T : Type> «std::meta::ctstring::AsCtString» for FmtString<T> as impl_282 {
  nr_def as_ctstring(self : FmtString<T>) -> Quoted<CtString> := {
    (fmtstr_as_ctstring<TV_'141, TV_'142> as λ(FmtString<T>) -> Quoted<CtString>)(self)
  }
}

