-- Generated by lampe

import Multiple.Extracted.Types
import Lampe

open Lampe

namespace Extracted

nr_def «baz»::«bang»::«bang»<>(x : Field) -> Field {
    #fAdd(x, 1 : Field) : Field;
}


def Baz.Bang.env := Lampe.Env.mk [«baz::bang::bang»] []