-- Generated by lampe

import Lampe

open Lampe

namespace Extracted

nr_def «baz»<>() -> Unit {
    let x = 3 : Field;
    (@bar<> as λ() → Unit)();
}

nr_def «bar»<>() -> Unit {
    let mut x = 3 : Field;
    x = 4 : Field;
    skip;
}

nr_def «foo»<>() -> Unit {
    let x = 3 : Field;
    skip;
}


def env := Lampe.Env.mk [«bar», «baz», «foo»] []
