-- Generated by lampe

import Lampe

open Lampe

namespace «Merkle-0.0.0»
namespace Extracted

nr_trait_def BinaryHasher<F> {
    fn hash<>(F, F) -> F
}

nr_trait_def Hasher<> {
        fn finish<>(Self) -> Field
        fn write<>(&Self, Field) -> Unit
}

nr_struct_def skyscraper::Skyscraper<> {

}