-- Generated by lampe

import «std-1.0.0-beta.25».Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

def «std-1.0.0-beta.25».Meta.TraitImpl.env : Env := Env.mk
  []
  []
