-- Generated by lampe

import «LocalDepWithLampe-2.0.0».Extracted.GeneratedTypes
import «LocalDepWithLampe-2.0.0».Extracted.Lib

namespace «LocalDepWithLampe-2.0.0»
namespace Extracted

def env := «LocalDepWithLampe-2.0.0».Extracted.Lib.env
