-- Generated by lampe

import Lampe

open Lampe

namespace «Patterns-0.0.0»
namespace Extracted

nr_struct_def Option1<T> {
    is_some : bool,
    value : T
}

nr_struct_def Option2<T> {
    is_some : bool,
    value : T
}