-- Generated by lampe

import «FieldGenerics-0.0.0».Extracted.GeneratedTypes
import «FieldGenerics-0.0.0».Extracted.Main

namespace «FieldGenerics-0.0.0»
namespace Extracted

def env := «FieldGenerics-0.0.0».Extracted.Main.env
