-- Generated by lampe

import «TestDep-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «TestDep-0.0.0»
namespace Extracted

noir_def main<>(x: Field, y: Field) -> Unit := {
  (#_assert returning Unit)((#_fNeq returning bool)(x, y));
  #_skip
}

noir_def test_main<>() -> Unit := {
  (main<> as λ(Field, Field) -> Unit)((1: Field), (2: Field));
  #_skip
}

def Main.env : Env := Env.mk
  [main, test_main]
  []
