-- Generated by lampe

import «TestDep-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «TestDep-0.0.0»
namespace Extracted

nr_def «main»<>(x : Field, y : Field) -> Unit {
    #assert(#fNeq(x, y) : bool) : Unit;
}

nr_def «test_main»<>() -> Unit {
    (@main<> as λ(Field, Field) → Unit)(1 : Field, 2 : Field);
}


def Main.env := Lampe.Env.mk [«main», «test_main»] []