-- Generated by lampe

import «Multiple-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «Multiple-0.0.0»
namespace Extracted

noir_def baz::bang::bang<>(x: Field) -> Field := {
  (#_fAdd returning Field)(x, (1: Field))
}


def Baz.Bang.env : Env := Env.mk
  [«baz::bang::bang»]
  []
