$RAISE_SUBPROC_ERROR = True

import argparse
from pathlib import Path
import os
import subprocess

# --- Start of copied part.
# This method is used to resolve the project's root directory,
# which is necessary for importing dependencies and other files.
# It is copied into every *.xsh file we use.
# If you make changes to this method, be sure to update all other
# copies as well.
def get_project_root():
    script_dir = Path($(echo $XONSH_SOURCE).strip()).resolve()
    root_dir = script_dir
    while True:
        if (root_dir / '.git').is_dir():
            return root_dir

        if root_dir.resolve() == Path('/'):
            raise Exception("Could not find .git directory in file tree")

        root_dir = root_dir.parent

# This is a hack for xonsh. This way we have global value
# initialized only once across all runs. It is required for some
# scripts that are being imported with source command and being
# run from directory outside of the project tree (like copied).
try:
    try_get_project_root = project_root
except NameError:
    project_root = get_project_root()
# --- End of copied part.

def get_script_dir():
    return project_root / "scripts"

LAMPE_GENERATED_COMMENT = "Generated by lampe"

def parse_args():
    parser = argparse.ArgumentParser(description='Run Lampe tests')
    parser.add_argument('-t', '--test', dest='test', help='Name of directory with test to run')
    parser.add_argument('-u', '--update', action='store_true', help='Legacy flag (no effect)')
    return parser.parse_args()

def run_tests(dir):
    args = parse_args()
    script_dir = project_root / dir
    test_cases_dir = script_dir

    selected_test = args.test or ""
    args.update  # legacy flag is ignored; extraction happens in place

    if 'LAMPE_TEST_CURRENT_COMMIT_SHA' not in ${...}:
        $LAMPE_TEST_CURRENT_COMMIT_SHA=$(git rev-parse HEAD)

    cd @(project_root)
    cargo build --release

    if selected_test == "":
        test_cases = []
        for item in test_cases_dir.iterdir():
            if item.is_dir() and not item.name.startswith('.') and item != test_cases_dir:
                test_cases.append(item)
    else:
        test_cases = [test_cases_dir / selected_test]

    for test_case in test_cases:
        run_test(test_case)

def find_lampe_dirs(dir_path):
    lampe_dirs = []
    root_lampe = dir_path / "lampe"
    if root_lampe.is_dir():
        lampe_dirs.append(root_lampe)
    for item in dir_path.iterdir():
        if item.is_dir():
            lampe_dir = item / "lampe"
            if lampe_dir.is_dir():
                lampe_dirs.append(lampe_dir)
    return sorted(lampe_dirs)

def assert_generated_extracts(lampe_dir):
    extracted_dirs = list(lampe_dir.glob("**/Extracted"))
    extracted_files = list(lampe_dir.rglob("Extracted.lean"))

    for extracted_dir in extracted_dirs:
        for lean_file in extracted_dir.rglob("*.lean"):
            contents = lean_file.read_text()
            if LAMPE_GENERATED_COMMENT not in contents:
                raise Exception(f"Non-generated file in extracted directory: {lean_file}")

    for extracted_file in extracted_files:
        contents = extracted_file.read_text()
        if LAMPE_GENERATED_COMMENT not in contents:
            raise Exception(f"Non-generated Extracted.lean file: {extracted_file}")

def run_test(dir_path):
    cd @(dir_path)
    dir_name = dir_path.name

    cli = project_root / "target" / "release" / "lampe"

    print("-" * 40)
    print(f"Running tests in {dir_name}...")
    print("-" * 40)

    if dir_name.startswith('_'):
        return

    if (dir_path / "clean.xsh").exists():
        /usr/bin/env xonsh @(dir_path / "clean.xsh") @(project_root)
    elif (dir_path / "clean.sh").exists():
        /usr/bin/env bash @(dir_path / "clean.sh")

    cmd = [str(cli), "--root", str(dir_path)]
    subprocess.run(cmd, check=True)

    if (dir_path / "user_actions.xsh").exists():
        /usr/bin/env xonsh @(dir_path / "user_actions.xsh") @(project_root)
    elif (dir_path / "user_actions.sh").exists():
        /usr/bin/env bash @(dir_path / "user_actions.sh")

    lampe_dirs = find_lampe_dirs(dir_path)
    if not lampe_dirs:
        raise Exception(f"No lampe/ directories found under {dir_path}")

    for lampe_dir in lampe_dirs:
        assert_generated_extracts(lampe_dir)

        lakefile_path = lampe_dir / "lakefile.toml"
        if lakefile_path.exists():
            lampe_path = os.path.relpath(project_root / "Lampe", lampe_dir)
            stdlib_path = os.path.relpath(project_root / "stdlib" / "lampe", lampe_dir)
            change_toml_required_dep_to_path_by_regex(lakefile_path, '^Lampe$', lampe_path)
            change_toml_required_dep_to_path_by_regex(lakefile_path, '^std-.*$', stdlib_path)

            rev = $LAMPE_TEST_CURRENT_COMMIT_SHA
            change_toml_required_dep_to_rev_by_regex(lakefile_path, '^GitDepWithLampe-.*$', rev)

        cd @(lampe_dir)
        lake exe cache get
        lake build
