-- Generated by lampe

import «std-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «std-0.0.0»
namespace Extracted

impl «std::cmp::Eq» for Field as impl_67 {
  nr_def eq(self : Field, other : Field) -> Bool := {
    fEq(self, other)
  }
}

impl «std::cmp::Eq» for u128 as impl_68 {
  nr_def eq(self : u128, other : u128) -> Bool := {
    uEq(self, other)
  }
}

impl «std::cmp::Eq» for u64 as impl_69 {
  nr_def eq(self : u64, other : u64) -> Bool := {
    uEq(self, other)
  }
}

impl «std::cmp::Eq» for u32 as impl_70 {
  nr_def eq(self : u32, other : u32) -> Bool := {
    uEq(self, other)
  }
}

impl «std::cmp::Eq» for u16 as impl_71 {
  nr_def eq(self : u16, other : u16) -> Bool := {
    uEq(self, other)
  }
}

impl «std::cmp::Eq» for u8 as impl_72 {
  nr_def eq(self : u8, other : u8) -> Bool := {
    uEq(self, other)
  }
}

impl «std::cmp::Eq» for u1 as impl_73 {
  nr_def eq(self : u1, other : u1) -> Bool := {
    uEq(self, other)
  }
}

impl «std::cmp::Eq» for i8 as impl_74 {
  nr_def eq(self : i8, other : i8) -> Bool := {
    iEq(self, other)
  }
}

impl «std::cmp::Eq» for i16 as impl_75 {
  nr_def eq(self : i16, other : i16) -> Bool := {
    iEq(self, other)
  }
}

impl «std::cmp::Eq» for i32 as impl_76 {
  nr_def eq(self : i32, other : i32) -> Bool := {
    iEq(self, other)
  }
}

impl «std::cmp::Eq» for i64 as impl_77 {
  nr_def eq(self : i64, other : i64) -> Bool := {
    iEq(self, other)
  }
}

impl «std::cmp::Eq» for Unit as impl_78 {
  nr_def eq(_self : Unit, _other : Unit) -> Bool := {
    true
  }
}

impl «std::cmp::Eq» for Bool as impl_79 {
  nr_def eq(self : Bool, other : Bool) -> Bool := {
    bEq(self, other)
  }
}

impl<N : U32, T : Type> «std::cmp::Eq» for Array<T, N> as impl_80 {
  nr_def eq(self : Array<T, N>, other : Array<T, N>) -> Bool := {
    let mut result : Bool = true;
    for i in (0 : u32) .. (len<TV_'253, TV_'252> as λ(Array<T, N>) -> u32)(self) do {
      skip
    }
    result
  }
}

impl<T : Type> «std::cmp::Eq» for Slice<T> as impl_81 {
  nr_def eq(self : Slice<T>, other : Slice<T>) -> Bool := {
    let mut result : Bool = uEq((len<TV_'225> as λ(Slice<T>) -> u32)(self), (len<TV_'225> as λ(Slice<T>) -> u32)(other));
    for i in (0 : u32) .. (len<TV_'225> as λ(Slice<T>) -> u32)(self) do {
      skip
    }
    result
  }
}

impl<N : U32> «std::cmp::Eq» for String<N> as impl_82 {
  nr_def eq(self : String<N>, other : String<N>) -> Bool := {
    let self_bytes : Array<u8, N> = (as_bytes<TV_'218> as λ(String<N>) -> Array<u8, N>)(self);
    let other_bytes : Array<u8, N> = (as_bytes<TV_'218> as λ(String<N>) -> Array<u8, N>)(other);
    (Array<u8, N>.eq as Bool)(self_bytes, other_bytes)
  }
}

impl<A : Type, B : Type> «std::cmp::Eq» for Tuple<A, B> as impl_83 {
  nr_def eq(self : Tuple<A, B>, other : Tuple<A, B>) -> Bool := {
    bAnd((A.eq<TV_'26> as λ(A, A) -> Bool)(Struct.get(self, 0), Struct.get(other, 0)), (B.eq<TV_'26> as λ(B, B) -> Bool)(Struct.get(self, 1), Struct.get(other, 1)))
  }
}

impl<A : Type, B : Type, C : Type> «std::cmp::Eq» for Tuple<A, B, C> as impl_84 {
  nr_def eq(self : Tuple<A, B, C>, other : Tuple<A, B, C>) -> Bool := {
    bAnd(bAnd((A.eq<TV_'26> as λ(A, A) -> Bool)(Struct.get(self, 0), Struct.get(other, 0)), (B.eq<TV_'26> as λ(B, B) -> Bool)(Struct.get(self, 1), Struct.get(other, 1))), (C.eq<TV_'26> as λ(C, C) -> Bool)(Struct.get(self, 2), Struct.get(other, 2)))
  }
}

impl<A : Type, B : Type, C : Type, D : Type> «std::cmp::Eq» for Tuple<A, B, C, D> as impl_85 {
  nr_def eq(self : Tuple<A, B, C, D>, other : Tuple<A, B, C, D>) -> Bool := {
    bAnd(bAnd(bAnd((A.eq<TV_'26> as λ(A, A) -> Bool)(Struct.get(self, 0), Struct.get(other, 0)), (B.eq<TV_'26> as λ(B, B) -> Bool)(Struct.get(self, 1), Struct.get(other, 1))), (C.eq<TV_'26> as λ(C, C) -> Bool)(Struct.get(self, 2), Struct.get(other, 2))), (D.eq<TV_'26> as λ(D, D) -> Bool)(Struct.get(self, 3), Struct.get(other, 3)))
  }
}

impl<A : Type, B : Type, C : Type, D : Type, E : Type> «std::cmp::Eq» for Tuple<A, B, C, D, E> as impl_86 {
  nr_def eq(self : Tuple<A, B, C, D, E>, other : Tuple<A, B, C, D, E>) -> Bool := {
    bAnd(bAnd(bAnd(bAnd((A.eq<TV_'26> as λ(A, A) -> Bool)(Struct.get(self, 0), Struct.get(other, 0)), (B.eq<TV_'26> as λ(B, B) -> Bool)(Struct.get(self, 1), Struct.get(other, 1))), (C.eq<TV_'26> as λ(C, C) -> Bool)(Struct.get(self, 2), Struct.get(other, 2))), (D.eq<TV_'26> as λ(D, D) -> Bool)(Struct.get(self, 3), Struct.get(other, 3))), (E.eq<TV_'26> as λ(E, E) -> Bool)(Struct.get(self, 4), Struct.get(other, 4)))
  }
}

impl «std::cmp::Eq» for «cmp::Ordering» as impl_87 {
  nr_def eq(self : «cmp::Ordering», other : «cmp::Ordering») -> Bool := {
    fEq(Struct.get(self, 0), Struct.get(other, 0))
  }
}

impl «std::cmp::Ord» for u128 as impl_88 {
  nr_def cmp(self : u128, other : u128) -> «cmp::Ordering» := {
    if uLt(self, other) then {
      (««cmp::Ordering»::less» as λ() -> «cmp::Ordering»)()
    } else if uGt(self, other) then {
      (««cmp::Ordering»::greater» as λ() -> «cmp::Ordering»)()
    } else {
      (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()
    }
  }
}

impl «std::cmp::Ord» for u64 as impl_89 {
  nr_def cmp(self : u64, other : u64) -> «cmp::Ordering» := {
    if uLt(self, other) then {
      (««cmp::Ordering»::less» as λ() -> «cmp::Ordering»)()
    } else if uGt(self, other) then {
      (««cmp::Ordering»::greater» as λ() -> «cmp::Ordering»)()
    } else {
      (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()
    }
  }
}

impl «std::cmp::Ord» for u32 as impl_90 {
  nr_def cmp(self : u32, other : u32) -> «cmp::Ordering» := {
    if uLt(self, other) then {
      (««cmp::Ordering»::less» as λ() -> «cmp::Ordering»)()
    } else if uGt(self, other) then {
      (««cmp::Ordering»::greater» as λ() -> «cmp::Ordering»)()
    } else {
      (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()
    }
  }
}

impl «std::cmp::Ord» for u16 as impl_91 {
  nr_def cmp(self : u16, other : u16) -> «cmp::Ordering» := {
    if uLt(self, other) then {
      (««cmp::Ordering»::less» as λ() -> «cmp::Ordering»)()
    } else if uGt(self, other) then {
      (««cmp::Ordering»::greater» as λ() -> «cmp::Ordering»)()
    } else {
      (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()
    }
  }
}

impl «std::cmp::Ord» for u8 as impl_92 {
  nr_def cmp(self : u8, other : u8) -> «cmp::Ordering» := {
    if uLt(self, other) then {
      (««cmp::Ordering»::less» as λ() -> «cmp::Ordering»)()
    } else if uGt(self, other) then {
      (««cmp::Ordering»::greater» as λ() -> «cmp::Ordering»)()
    } else {
      (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()
    }
  }
}

impl «std::cmp::Ord» for i8 as impl_93 {
  nr_def cmp(self : i8, other : i8) -> «cmp::Ordering» := {
    if iLt(self, other) then {
      (««cmp::Ordering»::less» as λ() -> «cmp::Ordering»)()
    } else if iGt(self, other) then {
      (««cmp::Ordering»::greater» as λ() -> «cmp::Ordering»)()
    } else {
      (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()
    }
  }
}

impl «std::cmp::Ord» for i16 as impl_94 {
  nr_def cmp(self : i16, other : i16) -> «cmp::Ordering» := {
    if iLt(self, other) then {
      (««cmp::Ordering»::less» as λ() -> «cmp::Ordering»)()
    } else if iGt(self, other) then {
      (««cmp::Ordering»::greater» as λ() -> «cmp::Ordering»)()
    } else {
      (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()
    }
  }
}

impl «std::cmp::Ord» for i32 as impl_95 {
  nr_def cmp(self : i32, other : i32) -> «cmp::Ordering» := {
    if iLt(self, other) then {
      (««cmp::Ordering»::less» as λ() -> «cmp::Ordering»)()
    } else if iGt(self, other) then {
      (««cmp::Ordering»::greater» as λ() -> «cmp::Ordering»)()
    } else {
      (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()
    }
  }
}

impl «std::cmp::Ord» for i64 as impl_96 {
  nr_def cmp(self : i64, other : i64) -> «cmp::Ordering» := {
    if iLt(self, other) then {
      (««cmp::Ordering»::less» as λ() -> «cmp::Ordering»)()
    } else if iGt(self, other) then {
      (««cmp::Ordering»::greater» as λ() -> «cmp::Ordering»)()
    } else {
      (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()
    }
  }
}

impl «std::cmp::Ord» for Unit as impl_97 {
  nr_def cmp(_self : Unit, _other : Unit) -> «cmp::Ordering» := {
    (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()
  }
}

impl «std::cmp::Ord» for Bool as impl_98 {
  nr_def cmp(self : Bool, other : Bool) -> «cmp::Ordering» := {
    if self then {
      if other then {
        (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()
      } else {
        (««cmp::Ordering»::greater» as λ() -> «cmp::Ordering»)()
      }
    } else if other then {
      (««cmp::Ordering»::less» as λ() -> «cmp::Ordering»)()
    } else {
      (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()
    }
  }
}

impl<N : U32, T : Type> «std::cmp::Ord» for Array<T, N> as impl_99 {
  nr_def cmp(self : Array<T, N>, other : Array<T, N>) -> «cmp::Ordering» := {
    let mut result : «cmp::Ordering» = (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)();
    for i in (0 : u32) .. (len<TV_'252, TV_'253> as λ(Array<T, N>) -> u32)(self) do {
      if («cmp::Ordering».eq as Bool)(result, (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()) then {
        skip
      }
    }
    result
  }
}

impl<T : Type> «std::cmp::Ord» for Slice<T> as impl_100 {
  nr_def cmp(self : Slice<T>, other : Slice<T>) -> «cmp::Ordering» := {
    let mut result : «cmp::Ordering» = (u32.cmp as λ(u32, u32) -> «cmp::Ordering»)((len<TV_'225> as λ(Slice<T>) -> u32)(self), (len<TV_'225> as λ(Slice<T>) -> u32)(other));
    for i in (0 : u32) .. (len<TV_'225> as λ(Slice<T>) -> u32)(self) do {
      if («cmp::Ordering».eq as Bool)(result, (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()) then {
        skip
      }
    }
    result
  }
}

impl<A : Type, B : Type> «std::cmp::Ord» for Tuple<A, B> as impl_101 {
  nr_def cmp(self : Tuple<A, B>, other : Tuple<A, B>) -> «cmp::Ordering» := {
    let result : «cmp::Ordering» = (A.cmp<TV_'27> as λ(A, A) -> «cmp::Ordering»)(Struct.get(self, 0), Struct.get(other, 0));
    if («cmp::Ordering».eq as Bool)(result, (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()) then {
      result
    } else {
      (B.cmp<TV_'27> as λ(B, B) -> «cmp::Ordering»)(Struct.get(self, 1), Struct.get(other, 1))
    }
  }
}

impl<A : Type, B : Type, C : Type> «std::cmp::Ord» for Tuple<A, B, C> as impl_102 {
  nr_def cmp(self : Tuple<A, B, C>, other : Tuple<A, B, C>) -> «cmp::Ordering» := {
    let mut result : «cmp::Ordering» = (A.cmp<TV_'27> as λ(A, A) -> «cmp::Ordering»)(Struct.get(self, 0), Struct.get(other, 0));
    if («cmp::Ordering».eq as Bool)(result, (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()) then {
      skip
    };
    if («cmp::Ordering».eq as Bool)(result, (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()) then {
      skip
    };
    result
  }
}

impl<A : Type, B : Type, C : Type, D : Type> «std::cmp::Ord» for Tuple<A, B, C, D> as impl_103 {
  nr_def cmp(self : Tuple<A, B, C, D>, other : Tuple<A, B, C, D>) -> «cmp::Ordering» := {
    let mut result : «cmp::Ordering» = (A.cmp<TV_'27> as λ(A, A) -> «cmp::Ordering»)(Struct.get(self, 0), Struct.get(other, 0));
    if («cmp::Ordering».eq as Bool)(result, (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()) then {
      skip
    };
    if («cmp::Ordering».eq as Bool)(result, (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()) then {
      skip
    };
    if («cmp::Ordering».eq as Bool)(result, (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()) then {
      skip
    };
    result
  }
}

impl<A : Type, B : Type, C : Type, D : Type, E : Type> «std::cmp::Ord» for Tuple<A, B, C, D, E> as impl_104 {
  nr_def cmp(self : Tuple<A, B, C, D, E>, other : Tuple<A, B, C, D, E>) -> «cmp::Ordering» := {
    let mut result : «cmp::Ordering» = (A.cmp<TV_'27> as λ(A, A) -> «cmp::Ordering»)(Struct.get(self, 0), Struct.get(other, 0));
    if («cmp::Ordering».eq as Bool)(result, (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()) then {
      skip
    };
    if («cmp::Ordering».eq as Bool)(result, (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()) then {
      skip
    };
    if («cmp::Ordering».eq as Bool)(result, (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()) then {
      skip
    };
    if («cmp::Ordering».eq as Bool)(result, (««cmp::Ordering»::equal» as λ() -> «cmp::Ordering»)()) then {
      skip
    };
    result
  }
}

nr_def «cmp::max»<T : Type>(v1 : T, v2 : T) -> T := {
  if (T.cmp as Bool)(v1, v2) then {
    v1
  } else {
    v2
  }
}

nr_def «cmp::min»<T : Type>(v1 : T, v2 : T) -> T := {
  if (T.cmp as Bool)(v1, v2) then {
    v2
  } else {
    v1
  }
}

