-- Generated by lampe

import «std-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «std-0.0.0»
namespace Extracted

nr_def «compat»::«is_bn254»<>() -> bool {
    true;
}


def Compat.env := Lampe.Env.mk [«compat::is_bn254»] []