-- Generated by lampe

import «std-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «std-0.0.0»
namespace Extracted

nr_def «ecdsa_secp256k1::verify_signature»<N : U32>(public_key_x : Array<u8, 32>, public_key_y : Array<u8, 32>, signature : Array<u8, 64>, message_hash : Array<u8, N>) -> Bool := {
  ecdsa_secp256k1(public_key_x, public_key_y, signature, message_hash)
}

nr_def «ecdsa_secp256k1::verify_signature_slice»(public_key_x : Array<u8, 32>, public_key_y : Array<u8, 32>, signature : Array<u8, 64>, message_hash : Slice<u8>) -> Bool := {
  ecdsa_secp256k1(public_key_x, public_key_y, signature, message_hash)
}

