-- Generated by lampe

import «std-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «std-0.0.0»
namespace Extracted

nr_def «hint»::«black_box»<T>(value : T) -> T {

}


def Hint.env := Lampe.Env.mk [«hint::black_box»] []