-- Generated by lampe

import «std-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «std-0.0.0»
namespace Extracted

nr_def «mem::zeroed»<T : Type>() -> T := {
  zeroed()
}

nr_def «mem::checked_transmute»<U : Type, T : Type>(value : T) -> U := {
  checked_transmute(value)
}

nr_def «mem::array_refcount»<N : U32, T : Type>(array : Array<T, N>) -> u32 := {
  array_refcount(array)
}

nr_def «mem::slice_refcount»<T : Type>(slice : Slice<T>) -> u32 := {
  slice_refcount(slice)
}

