-- Generated by lampe

import «std-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «std-0.0.0»
namespace Extracted

nr_def «panic»::«panic»<T, U, @N : u32>(message : fmtstr<N:u32, T>) -> U {
    #assert(false) : Unit;
    (@std::mem::zeroed< U > as λ() → U)();
}


def Panic.env := Lampe.Env.mk [«panic::panic»] []