name = "example1"
version = "0.1.0"
defaultTargets = ["Merkle"]

[[lean_lib]]
name = "Merkle"

[[require]]
name = "Lampe"
rev = "main"
path = "../../Lampe/"
# In a real setup, require Lampe like this:
# git = "https://github.com/reilabs/lampe"
# subDir = "Lampe"

[[require]]
name = "proven-zk"
rev = "4.15"
git = "https://github.com/reilabs/proven-zk"
