-- Generated by lampe

import «std-1.0.0-beta.25».Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_struct_def «Merkle-1.0.0»::skyscraper::Skyscraper<> {}

noir_trait_def «Merkle-1.0.0»::hasher::BinaryHasher<F: Type> [] := {
  method hash<>(F, F) -> F;
}

noir_trait_def «Merkle-1.0.0»::hasher::Hasher<> [] := {
  method finish<>(Self) -> Field;
  method write<>(& Self, Field) -> Unit;
}

