-- Generated by lampe

import «std-1.0.0-beta.3».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «std-1.0.0-beta.3»
namespace Extracted

noir_trait_impl[impl_66]<N: u32> std::convert::From<Array<u8, N: u32> > for String<N: u32> where [] := {
  noir_def from<>(bytes: Array<u8, N: u32>) -> String<N: u32> := {
    (std::array::as_str_unchecked<> as λ(Array<u8, N: u32>) -> String<N: u32>)(bytes)
  };
}


def String.env : Env := Env.mk
  []
  [impl_66]
